### ISSUE TITLE
Trouble with disqus

### ISSUE THREAD

**Issue by Skahrz** [jekyll/minima#104]
I m starting to create a simple github page on my github name like https://skahrz.github.io

I m using your minimalist (but really cool) theme. 

Actually, I m having some troubles dealing with the disqus integration. For now, here's my _config.yml config :

```
title: On parle de code :)
email: email@mail.com
description: Javascript & Clean Code :O
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: skahrn
github_username:  skahrz
disqus:
  shortname: skahrz-github
google_analytics: ANALYTICS_ID
# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
```

When I m trying to load disqus on my website, it doesn't load and ask me to follow some troubleshooting guides (what I did) but it doesn't work as expected, without throwing some weird errors : 

https://skahrz.github.io/jekyll/update/2017/01/30/welcome-to-jekyll.html

My configuration on disqus are the following :

<img width="732" alt="capture d ecran 2017-01-31 a 07 01 08" src="https://cloud.githubusercontent.com/assets/3874873/22454000/286b909c-e783-11e6-8419-f0d6538bead7.png">

But nothing happens... Am I missing something in my config file ?

**Comment by ashmaroli** [comment]
Your Jekyll configurations look correct to me.

But your Disqus configuration seems incorrect: The troubleshooting guide says you've to set the domain as `skahrz.github.io` instead of `https://skahrz.github.io`.
Note: Changing it will require you to wait about 48hours for it to take effect.

**Comment by joesasson** [comment]
I'm gonna add to this answer because I just encountered the same problem. You need to set the `url` property in the `config.yml` that you posted above to the your blog url:

`url: "https://skahrz.github.io"` should do the trick.

**Comment by Sathors** [comment]
I can confirm that setting the url resolves the problem.

**Comment by Skahrz** [comment]
Wow, I m really late, sorry about that. And yes , adding the url solved my problem :)

**Comment by Funeoz** [comment]
I changed the url to mine but it still doesn't work. Any solutions?
