### ISSUE TITLE
Hamburger not working on iOS

### ISSUE THREAD

**Issue by janegilring** [jekyll/minima#105]
Are there any known issues with the hamburger menu not working on iOS? It works fine from Android, but not iOS for [my site.](http://www.powershell.no)

**Comment by DirtyF** [comment]
See #80 #85 and [all](https://github.com/jekyll/minima/search?utf8=%E2%9C%93&q=HAmburger&type=Issues)

**Comment by janegilring** [comment]
Thanks!
