### ISSUE TITLE
h2 has a larger font than h1 in Chrome

### ISSUE THREAD

**Issue by quanticle** [jekyll/minima#113]
I see in layout.scss that Minima is forcing `.post-content h2` to 32px. However, I don't see a similar rule for `.post-content h1`. This means that by default, in Chrome, `h2` elements are larger than `h1`s, because Chrome's default size for `h1` is 24px. Is this intentional?

**Comment by domingohui** [comment]
+1. I don't see a difference between h1 and h2 in chrome.

**Comment by ashmaroli** [comment]
While this issue is valid, the reason is, one expects to use `<h1>` only once per page and that is used within the `layout` itself to display `{{ page.title }}`. 
Headings in the content documents should then ideally start with `<h2>`

[Example Preview](https://jekyll.github.io/minima/History.html)

**Comment by DirtyF** [comment]
The `post-title` class applied on the h1 on the post layout is set to 36px.
and `.post-content h2` is set to 32px. I don't see any issue here.

**Comment by ashmaroli** [comment]
I think the issue according to the OP is when the markdown document itself contains an `<h1>`, which would then translate to `post-content h1`
```
# Heading 1
## Heading 2
```
```
<div class="post-content">
  <h1>Heading 1</h1>
  <h2>Heading 2</h2>
</div>
```

**Comment by antgel** [comment]
What @ashmaroli said - it's natural to use # in markdown. It doesn't seem realistic to assume that the user will know that `#` renders as `<h1>` and multiple `<h1>`s are frowned upon. Where does the responsibility lie for getting this right? jekyll? minima? markdown? It should at least be documented somewhere, if it's not something that can or will be solved in code.

**Comment by robinmetral** [comment]
Just a note that this issue is not only relevant to Chrome but also to Firefox.

I strongly agree with @antgel here. The Minima theme can not change how markdown generates HTML, but it can at least make `<h1>` elements appear larger than `<h2>` elements, no matter what. This should be the priority here.

Then of course in term of semantics, while it is actually [not a problem to have several `<h1>` on a single page](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Using_HTML_sections_and_outlines#Defining_sections), each `<h1>` should be the main heading of a sectioning element such as `<section>` or `<article>`. This is for Markdown to think about.

**Comment by victoriastuart** [comment]
I agree that the ability to specify a H1 header size that appears larger than H2 in markdown documents is a no-brainer!  In case this helps anyone else, I modified my `.../_sass/minima/_layout.scss` file as follows (adding the h1 code and tweaking the font sizes per my preference):

```
  h1 {
    @include relative-font-size(2.5);

    @include media-query($on-laptop) {
      @include relative-font-size(2.00);
    }
  }

  h2 {
    @include relative-font-size(2);

    @include media-query($on-laptop) {
      @include relative-font-size(1.75);
    }
  }

  h3 {
    @include relative-font-size(1.625);

    @include media-query($on-laptop) {
      @include relative-font-size(1.375);
    }
  }

  h4 {
    @include relative-font-size(1.25);

    @include media-query($on-laptop) {
      @include relative-font-size(1.125);
    }
  }
```

I hope it works for others.  I've attached a screenshot of a markdown file (with some dummy headers temporarily added, for comparison), and the rendered HTML.

![jekyll-minima-h1_header](https://user-images.githubusercontent.com/2575920/45178369-4db4ba00-b1ca-11e8-9dc9-2a9c73cd3c52.png)
