### ISSUE TITLE
icon-twitter.svg not being shown

### ISSUE THREAD

**Issue by jaydub255** [jekyll/minima#114]
I'm just beginning to setup​ Jekyll (3.4.2) with the default minima theme (2.1.0) on a fresh archlinux. I installed Ruby (2.4.0) and followed the quick start guide at jekyllrb.com - [gem install jekyll bundler && jekyll new ...]
However, the resulting page on localhost does not show the twitter icon in the footer. GitHub icon is there. Any ideas, please?

**Comment by ashmaroli** [comment]
the twitter icon will be displayed only if the `twitter_username:` is properly configured in your `_config.yml`
