### ISSUE TITLE
The hamburger is displayed even if there are no site.pages

### ISSUE THREAD

**Issue by Adyg** [jekyll/minima#115]
If there are no site.pages defined, the hamburger menu serves no purpose. Clicking it will do nothing.
Suggesting not including the nav tag at all if there are no links to populate it with.

**Comment by Adyg** [comment]
PR for this at https://github.com/jekyll/minima/pull/116.

**Comment by DirtyF** [comment]
@Adyg Have you successfully tested #116? I don't remember this hiding the nav during my tests.
