### ISSUE TITLE
localhost:4000/minima does not resolve correctly per README

### ISSUE THREAD

**Issue by jglovier** [jekyll/minima#119]
The readme says:

>To test your theme, run bundle exec rake preview and open your browser at ` http://localhost:4000/minima/`.

...however that does not resolve correctly:

![image](https://cloud.githubusercontent.com/assets/1319791/24813764/5063b022-1b9d-11e7-9bd4-5a3547797f0b.png)

...but `http://localhost:4000` does resolve to the theme preview instead:

![image](https://cloud.githubusercontent.com/assets/1319791/24813792/69207136-1b9d-11e7-8b12-25bbc4a670a7.png)

Not sure if this is something specific to my machine, or if we should update the README?

**Comment by DirtyF** [comment]
yeah `baseurl` has just been reset, we should update the README. Good catch!
