### ISSUE TITLE
Disqus Unable to Load on Post Page

### ISSUE THREAD

**Issue by Schwad** [jekyll/minima#125]
# Versions

* jekyll 3.4.0
* minima ~> 2.0

# _config.yml

```
title: Schwad
email: nicholas.schwaderer@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a Full Stack Ruby on Rails Software Engineer for OceansHQ in Torpoint,
  England.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://schwad.github.io
twitter_username: Schwad4HD14
github_username:  schwad
disqus:
  shortname: schwad-github-io

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
```

# repo

https://www.github.com/schwad/schwad.github.io

# Problem

![screen shot 2017-04-12 at 14 33 41](https://cloud.githubusercontent.com/assets/7865030/24960230/118587c4-1f8d-11e7-9d47-5daf3fce1691.png)

Disqus will not load on any of my pages. 

My shortname is valid as you can see by visiting: https://schwad-github-io.disqus.com

I have attempted to resolve this using the Jekyll docs, Github docs and Disqus docs, as well as querying and making tweaks around form reviewing StackOverflow. I have even attempted manually setting up disqus in my application, and clearing my cache and viewing incognito. 

I have spent about a week trying to debug this before bringing this issue to you, I certainly hope you can help me and provide some guidance on this issue.

All the best.

**Comment by Schwad** [comment]
And of course I would find the solution within 30 seconds of writing it out here. The only change I can imagine is that there was an extra whitespace in the line above with `github_username`. After I cleared that out it started working. Leaving here if anyone else makes the same mistake in the future. WHEW

**Comment by adrenalinehit** [comment]
unbelievable, but simply reapplying the changes in the _config.yml file worked for me too....weird!
