### ISSUE TITLE
Encoding problem when visiting 404 page

### ISSUE THREAD

**Issue by ouvek-kostiva** [jekyll/minima#126]
Encoding is fine when accessing the 404 page directly from /404.

When actually typing in a random url, 404 page doesn't display correctly (non-English parts).

**Comment by ashmaroli** [comment]
Hi,
Can you please explain what you mean by `doesn't display correctly (non-English parts).`? Can you provide a screenshot?

**Comment by ouvek-kostiva** [comment]
Apparently it's alright on github. When I tried it on cloud9, this was what it looked like.

![screenshot from 2017-04-19 01-46-50](https://cloud.githubusercontent.com/assets/5715022/25147996/092d5280-243f-11e7-8317-3fe082d17871.png)

**Comment by ashmaroli** [comment]
@ouvek-kostiva Does the remaining pages render properly on cloud9?

**Comment by DirtyF** [comment]
No response, closing.
