### ISSUE TITLE
Content of index should be in an index layout, not in an `index.html` file

### ISSUE THREAD

**Issue by benbalter** [jekyll/minima#13]
That way, `jekyll new` can just create an `index.md` file with:

```
---
layout: home
---
```

And we avoid hard-coding theme-specific HTML in the theme index (and I assume other themes will follow this theme's design pattern, since it's the default).

**Comment by ashmaroli** [comment]
I did feel it to be weird having to change both index.html and theme files when creating a new theme

**Comment by ashmaroli** [comment]
Hi, I've an open [PR](https://github.com/jekyll/jekyll/pull/5203) dealing with modifying the new command. Should I incorporate a change related to this issue?

**Comment by desiredpersona** [comment]
Hey Ben, Great idea. This seems to cause an issue with jekyll-paginate gem as it cant find index.html
```
Pagination: Pagination is enabled, but I couldn't find an index.html page to use as the pagination template. Skipping pagination.
```

**Comment by benbalter** [comment]
To be clear, I'm primarily suggesting we move the layout of the index page from `index.html` file to a layout, so that downstream users don't have to copy/paste. While I'd like it to be `index.md`, if that doesn't work with Jekyll-Paginate, so be it.

**Comment by desiredpersona** [comment]
Thanks Ben.

**Comment by parkr** [comment]
@benbalter I think this is more inflexible for the end user – what if you want to put an intro above your posts listing? I think an include is more appropriate here.

**Comment by benbalter** [comment]
>  I think this is more inflexible for the end user – what if you want to put an intro above your posts listing? I think an include is more appropriate here.

I guess, from my perspective, I see users adding minima to either an existing site, or a new site, in which right now, you have to copy/paste a lot, none of which we describe in the documentation (and would have to copy/paste to customize in either case).

I'm also guessing, from your perspective, you see using only getting to minima via `jekyll new` in which case you wouldn't have to copy/paste to customize. But the other downside is that we're hard coding content that should be in this repo into Jekyll, and even worse, into a script that writes it to the user's disk (and repo), meaning it's nearly impossible for downstream users to benefit form upstream changes to the template (the whole point of the themes in the first place).

**Comment by parkr** [comment]
> But the other downside is that we're hard coding content that should be
in this repo into Jekyll, and even worse, into a script that writes it to
the user's disk (and repo), meaning it's nearly impossible for downstream
users to benefit form upstream changes to the template (the whole point of
the themes in the first place).

Sounds like what you'd like to see is a way that each theme could specify
its own subcommand or template for `jekyll new`. This would allow the theme
owner control over what the user gets and what the user doesn't get.


-- 
Parker

**Comment by ashmaroli** [comment]
Handling in #48 and jekyll/jekyll#5420
