### ISSUE TITLE
Changing minima icon

### ISSUE THREAD

**Issue by AidanRocke** [jekyll/minima#133]
Is there any way to change the default icon? Right now it looks like a piece of paper with a corner folded in. 

I'd like to know whether this can be changed.

**Comment by ashmaroli** [comment]
Adding a `favicon.ico` image file to the root of your site should resolve this.
Google Favicon generators to create one from your site's logo (if any)

**Comment by AidanRocke** [comment]
Thanks.

**Comment by DirtyF** [comment]
@AidanRocke FYI here are some useful services for favicons:

- https://realfavicongenerator.net/
- https://favicon.io/
