### ISSUE TITLE
CSS for tables

### ISSUE THREAD

**Issue by adamvoss** [jekyll/minima#135]
On a couple different minima-based sites, have noticed that there seems to be no styling provided at all for tables, giving results that are generally not satisfactory.  On a theme where everything seems to just work well out of the box, this is a surprise.

Is there any chance better styling for tables could be provided?

I have assumed this to be a breaking change so can't be done at this point, but I noticed no one has yet raised an issue on it, so figured it was worth bringing up once.

**Comment by sethjackson** [comment]
I too would like to see some styling on tables.

**Comment by ashmaroli** [comment]
Sent a PR for this. Feedback appreciated :smiley:
