### ISSUE TITLE
Add Open Graph tags

### ISSUE THREAD

**Issue by mohd-akram** [jekyll/minima#138]

**Comment by DirtyF** [comment]
You can add Open Graph by adding [jekyll-seo-tag](https://github.com/jekyll/jekyll-seo-tag) plugin:

1. Add `jekyll-seo-tag` to your `Gemfile`:

```ruby
group :jekyll_plugins do
  gem 'jekyll-seo-tag'
end
```

2. Run `bundle update`
3. Create `_includes/head.html` with the following content to override theme's file:

```liquid
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  {% seo %}

  <link rel="stylesheet" href="{{ "/assets/main.css" | relative_url }}">

  <link rel="alternate" type="application/rss+xml" title="{{ site.title | escape }}" href="{{ "/feed.xml" | relative_url }}">

  {% if jekyll.environment == 'production' and site.google_analytics %}
  {% include google-analytics.html %}
  {% endif %}
</head>
```

4. You're done. You now have Open Graph tags inserted. See plugin documentation for further configuration.

@jekyll/minima: Should we do this by default?

**Comment by benbalter** [comment]
> Should we do this by default?

I believe in 3.5 themes can require their own dependencies. If Minima can specify that it requires the SEO plugin, that'd be my preferred approach.
