### ISSUE TITLE
Make minima a Progressive Web App

### ISSUE THREAD

**Issue by DirtyF** [jekyll/minima#149]
Following discussion on #145 

[Progressive Web Apps](https://developers.google.com/web/progressive-web-apps/)  aims at providing a better user experience on the web by providing offline support, home screen button and push notifications for already mobile-friendly websites. Offline support and push notifications are provided through a Service Worker (a standard JavaScript API). 

As GitHub pages offers HTTPS support, it's possible to enhance a responsive website and turn it into a PWA. All you need is to write [some generic JavaScript and some Liquid](https://jamesiv.es/jekyll/amp/2017/05/09/serviceworkers-with-jekyll.html) to generate the `sw.js` file. A `manifest.json`file will be used for the home screen button. You can also imagine pushing a notification for a new post (eg. a new Jekyll release on jekyllrb.com 😄 )

In order to do so, a theme has to provide:

- HTTPS (GitHub Pages does that)
- some favicons and a [manifest.json](https://w3c.github.io/manifest/) file 
- a offline.html page (very much like a 404.html)
- a service worker, the `sw.js` file could be generic or customizable (as you have to list the file you want the browser to serve offline, e.g. assets, the last posts, some pages, etc. You also have to generate a cache version (through a timestamp for instance) to invalidate the previous cache.

If we want to allow this on GitHub Pages, we cannot rely on a gem like [jekyll-offline](https://github.com/jeremiak/jekyll-offline) which I tested a while back and it wasn't satisfying.

**Comment by pathawks** [comment]
Why is including this in a theme better than making it available as a plugin?

**Comment by DirtyF** [comment]
@pathawks It isn't. 😄  

If you prefer we could break this issue in two parts and just rely on a quality plugin (that doesn't exist yet) for the offline and cache invalidation part.

**Comment by ashawley** [comment]
Franks says the jekyll-offline gem "wasn't satisfying" and a plugin would be better, but would a plugin be possible?  As written, #234 wouldn't be of much use to someone using minima as a Jekyll theme.
