### ISSUE TITLE
Loads the same favicon from the base Github Pages URL.

### ISSUE THREAD

**Issue by alchermd** [jekyll/minima#155]
Hi!

I'm using jekyll to create a blog with Github Pages. I added a `favicon.ico` file (per #133) to the root directory. This achieved the desired output when running the local dev server. But when viewing it in Github Pages through `my-name.github.io/myblog`, it uses the same favicon as `my-name.github.io`.

Any hints on how do I fix this?

**Comment by DirtyF** [comment]
Make sure you point to the right favicon in the blog meta tags?

Closing this as this is not related to `minima` itself. Feel free to contact GitHub Support if you think it's related to GitHub Pages.
