### ISSUE TITLE
Honor Do Not Track for Google Analytics

### ISSUE THREAD

**Issue by MikkCZ** [jekyll/minima#158]
According to this [post](https://www.reddit.com/r/analytics/comments/5qun9r/how_to_make_analytics_scripts_respect_do_not_track/), it should be easy to implement honoring of Do Not Track in JS. This can be of course configurable in `_config.yml`.

I can implement this, if you want. What should be the default - honor DNT, or not?

**Comment by DirtyF** [comment]
Thanks @MikkCZ for the suggestion.

The code snippet seems to follow [the specification](https://www.w3.org/2011/tracking-protection/drafts/tracking-dnt.html#js-dom) indeed.

I'm not sure about adding another config parameter though. People that enable DNT certainly have also installed browser extensions that will block analytics scripts. So here we just should respect end user's privacy choice.

**Comment by pathawks** [comment]
Does Google Analytics not already honor DNT?

**Comment by DirtyF** [comment]
@pathawks I don't think so. Google provides a [Chrome extension](https://chrome.google.com/webstore/detail/google-analytics-opt-out/fllaojicojecljbmefodhfapmkghcbnh?hl=en) to opt out.

I asked on [analytics.js issue tracker](https://issuetracker.google.com/issues/65485261) if they intend to do so, but it's very unlikely I guess.
