### ISSUE TITLE
Customizing Issue

### ISSUE THREAD

**Issue by Kraedt** [jekyll/minima#161]
Hello, I am new to Jekyll and I'm trying to set up custom CSS for my site. I followed the customize CSS directions perfectly, but I'm getting some weird error.

Here is my main.scss file that's in <root>/assets (after the front-matter lines)

> @import "minima";
>.test {
>  color: red;
>}

And this is the error I get (that also shows up in main.css)
`Error: Invalid CSS after "@import "minima"": expected "{", was ";"
        on line 4 of main.scss`

My head.html that's in <root>/_includes correctly points to the custom scss file
`    <link rel="stylesheet" href="../assets/main.css">`

This is extremely confusing to me and I'm on the verge of giving up. If someone could help me figure this out, that'd be great. Thanks.

**Comment by DirtyF** [comment]
Hi

I cannot reproduce your issue if I copy the files from the Gem and add a new CSS rule, it works fine.

I suggest you copy the original head.html and customize it to your needs but keep the call to CSS as it is:
https://github.com/jekyll/minima/blob/master/_includes/head.html#L6

```
---
# assets/main.scss
---

@import "minima";

.post-title {
  color: red;
}
```

**Comment by Kraedt** [comment]
Thanks DirtyF,

I've tried exactly that (with the original head.html) and I'm still getting the same error. I think it works better for me to skip the theme and just do my own CSS from scratch, anyways.

**Comment by DirtyF** [comment]
Out of curiosity what versions are you running, which OS are you running?

`ruby -v`

`bundle exec jekyll -v`

**Comment by Kraedt** [comment]
> ruby 2.4.2p198 (2017-09-14 revision 59899) [x64-mingw32]
>jekyll 3.6.0
>Windows 10 64bit

**Comment by DirtyF** [comment]
Just checked out your repo, you have to remove the `main.css` file from your `assets` folders and just keep the `.scss` file there. It generates a conflicts and `main.css` takes precedence over `main.scss`.

I opened a PR for you to test the fix.

**Comment by Kraedt** [comment]
Thanks Frank, but I'm still getting the same error. I deleted the generated main.css file, but that doesn't help. Also, the main.css file keeps being generated for some reason.

**Comment by DirtyF** [comment]
@Kraedt That's related to your setup to the theme or Jekyll, sorry if I can't be of any help here.

**Comment by Kraedt** [comment]
Sounds likely. Thanks for trying, anyways.

**Comment by DirtyF** [comment]
https://kraedt.github.io/ works fine.

**Comment by Kraedt** [comment]
Oh yeah, I totally forgot to check that. I wonder why it's not showing properly on localhost?
