### ISSUE TITLE
Collections are invisible by default

### ISSUE THREAD

**Issue by antgel** [jekyll/minima#163]
When using the Collections feature of Jekyll, if I want to actually see links to my collections anywhere, I have to start editing templates. Not a crime in and of itself, but a bit unwieldy for the new user. Pages are automagically linked to in `_includes/header.html`, could a similar thing be done for collections?

**Comment by DirtyF** [comment]
> Minima is a one-size-fits-all Jekyll theme for writers

Displaying collections is not the initial intent of the theme, but as it's the default Jekyll theme and that collections are one of Jekyll's most interesting feature I understand that you would want it to display collections by default.  

Did you come with something you think would be useful to [hundred of thousands of users](https://rubygems.org/gems/minima)?

**Comment by antgel** [comment]
Hi, I'm not sure I understand what you mean by "did you come with something". Can you elaborate?

**Comment by DirtyF** [comment]
How would you make posts, collections and pages visible by default?

**Comment by antgel** [comment]
You mean from a UX perspective? I couldn't tell you offhand. I was kind of hoping (not in a lazy way) that people here would be able to "translate" such a requirement into a suitable UX.

My naive default approach (knowing little about UX / Minima's philosophy, codebase, etc) would be to have a couple of drop-downs where the `page.title`s currently go, at the top-right of the design. One for Pages and one for Collections.

**Comment by TotallyInformation** [comment]
I would certainly want to be able to include collections into the nav menu. At least to see a link to the collection itself `/:collection`. Perhaps a further option to expose collection documents as well though a 2-level menu would be helpful there.

If showing collection documents though, it might be necessary to have an option to filter documents, at least by extension.

Having said that, there do appear to be some significant problems with collections at the moment so, having spent some painful time trying to work out what the heck they do and don't do, I think I'm going to have to revert to pages. See [Jekyll issue 6661](https://github.com/jekyll/jekyll/issues/6661) for details.

**Comment by DirtyF** [comment]
We're not considering adding collections support in minima. 
We might though with another theme.
