### ISSUE TITLE
[Question] Does google analytics work or not?

### ISSUE THREAD

**Issue by lolgear** [jekyll/minima#166]
Well, I don't understand If GA works or not.

I added in `_config` google_analytics: UA-NNNN-N and made push.

Now I can see in article html:

```html
      <script type="text/javascript">
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-NNNNNN-N', 'auto');
        ga('send', 'pageview');
      </script>
    
  </body>
```

I suppose that I have zero views, but if I opened site, it still shows count zero views in analytics.google.com

Maybe an issue with `Jekyll environment variable` that should be production?
But I don't manage it and use GitHub pages.

Thanks for explanation!

**Comment by nickmccurdy** [comment]
https://github.com/jekyll/minima/blob/master/_includes/head.html#L8

Looks like you need to set the environment to production.

**Comment by DirtyF** [comment]
minima avoids to embed Analytics only in the development environment (the default when you run Jekyll locally), but you don't have to specify production environment as you can see, the script is embedded in your page, so everything is fine on our end.

Maybe you have a browser extension that blocks your script.

**Comment by lolgear** [comment]
@DirtyF oh, nice, thanks!
Yes, it works!
I just change safari with ublock origin to chrome!

It could be closed. ( And/Or wiki notes could be expanded by this check that script should appear in .html on site )

**Comment by nickmccurdy** [comment]
Note that you can optionally configure ublock origin to not block analytics by disabling the analytics list (though you may want this if you want to stop trackers for privacy or development purposes)

**Comment by DirtyF** [comment]
Glad you figured it out, closing then.  Thanks @nickmccurdy for helping on support ❤️
