### ISSUE TITLE
Zoom problem on Github Pages

### ISSUE THREAD

**Issue by melaniewalsh** [jekyll/minima#168]
My Jekyll site renders fine locally, but I can't figure out why it's so zoomed out on Github Pages. Doesn't anyone have any suggestions? I'd really appreciate it.

Here's my site (http://melaniewalsh.org/) and the code for my site (https://github.com/melaniewalsh/melaniewalsh.org)

**Comment by DirtyF** [comment]
Your website looks fine, default text is 16px, it's the base font-size defined in your Sass file.

**Comment by melaniewalsh** [comment]
Thanks for taking the time to check it out!

I wonder if it's a Chrome-specific problem. Because I just looked at my website in Safari, and it looks fine there, but it's still smaller and zoomed out in my Chrome browser.

**Comment by DirtyF** [comment]
Looks like your browser zoom level is not at 100%. 

![melaniewalsh](https://user-images.githubusercontent.com/103008/32572689-ab7a97c8-c4cb-11e7-98d6-127a976e6412.png)

I'm closing this issue then, as this does not seem related to the theme.
