### ISSUE TITLE
Site should look to `site.github.url` if it exists, and if not, fall back to `baseurl`

### ISSUE THREAD

**Issue by benbalter** [jekyll/minima#17]
This would allow project pages to work out of the box on GitHub Pages without requiring additional configuration (and wouldn't upset the local development experience or the experience of those using Jekyll outside of GitHub Pages).

**Comment by anthonyjsmith** [comment]
Just commented on the pull request - maybe more appropriate here (sorry for duplication):

I think that having a full URL (with `site.url`) in the stylesheet link causes a default Jekyll site to look for a stylesheet at `http://example.com/css/main.css`, which obviously doesn't exist. See [this Jekyll Talk thread](https://talk.jekyllrb.com/t/jekyll-build-does-not-create-complete-default-directory-structure/2953/2).
