### ISSUE TITLE
Application Insights support

### ISSUE THREAD

**Issue by arturmiz** [jekyll/minima#171]
There is already support for Google Analytics, how about adding support for [Application Insights](https://azure.microsoft.com/en-us/services/application-insights/)?

I think it may be an interesting alternative especially if someone uses Azure to host his minima blog.

**Comment by DirtyF** [comment]
Google Analytics is an exception, like Disqus. Those services were added because they are used by a vast majority. We don't plan to add other external services for now. 
Minima has to live by its name 😄
