### ISSUE TITLE
_config.yml having build errors

### ISSUE THREAD

**Issue by varshaneya** [jekyll/minima#172]
The _config.yml is having build errors when built using github. Please let me know what I am missing in _config.yml. Thanks in advance

**Comment by DirtyF** [comment]
Please [contact GitHub Support](https://github.com/contact?form%5Bsubject%5D=GitHub%20Pages) if you have trouble with GitHub Pages.

**Comment by varshaneya** [comment]
I took code for _config.yml from anderj karpathy  and it worked!! My site is now up and running. Can you add search feature to minima theme?

**Comment by DirtyF** [comment]
Glad you figured it out. Search would involves JS we do no want to add unnecessary dependencies to a theme designed to be minimal but you'll find some easy solutions to implement.
