### ISSUE TITLE
How about a Guide for someone to install this on Github Project (gh-pages)?

### ISSUE THREAD

**Issue by pwaugh** [jekyll/minima#185]
I have a tutorial I really want to "blog", on the repository I'll use for the code.  I have spent the last two weekends attempting to figure out the git commands needed to get this thing up and running on github, and have about given up.  I first tried the Minima theme from the Jekyll site, and then found this one.  At one point, I got the Jekyll version up and working, except the css was not being found.  And frankly, I never learned the more complicated git (I used mercurial and bitbucket), as I was using BitBucket.
Since I have a 10 hour/day day job, I don't really get much time and would be nice to have a walk-through guide to get this up and running on a gh-pages branch on a Repository Page (vs. the account/organization page on the master branch), and have it work.
All the stuff I'm finding on google is so out of date it's not helping.
Would be a logical addition to this repository!

**Comment by ashawley** [comment]
> Since I have a 10 hour/day day job, I don't really get much time and would be nice to have a walk-through guide to get this up and running on a gh-pages branch on a Repository Page

There are existing pages on other sites.  They could definitely be improved, where the reader may not know git or GitHub.  Maybe reach out to Jekyll or Github to improve them?

https://help.github.com/articles/using-jekyll-as-a-static-site-generator-with-github-pages/
https://jekyllrb.com/docs/github-pages/

**Comment by pwaugh** [comment]
Turned out was a Github issue, and my site is actually working.

Still, I urge you guys to "complete" the package by including an up-to-date guide.

**Comment by ashawley** [comment]
This repo is just a Jekyll theme, so you probably aren't petitioning the right people.

I'd suggest you open an issue at http://github.com/jekyll/jekyll and recommend the GitHub Pages section be improved, so it is more of a step-by-step guide.  The page it links to by Jonathan McGlone doesn't seem helpful or up-to-date, with all due respect.  That's the repo that maintains the site for this page, https://jekyllrb.com/docs/github-pages/
