### ISSUE TITLE
Jekyll builds failing since 2.2.0 released

### ISSUE THREAD

**Issue by kt-ssp** [jekyll/minima#187]
I have a scheduled task in Gitlab that builds a Jekyll project that started failing last night (~21:00 GMT). Checking the logs, the key difference was a change in the version of minima from 2.1.1 to 2.2.0. In the logs, I am now seeing:

```
Fetching jekyll-seo-tag 2.4.0
Installing jekyll-seo-tag 2.4.0
Fetching minima 2.2.0
Installing minima 2.2.0
Bundle complete! 4 Gemfile dependencies, 24 gems now installed.
Bundled gems are installed into `/usr/local/bundle`
$ bundle exec jekyll build -d public
Configuration file: /builds/{me}/pages/_config.yml
            Source: /builds/{me}/pages
       Destination: public
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/main.scss':
                    Undefined variable: "$table-text-align". on line 222
jekyll 3.6.2 | Error:  Undefined variable: "$table-text-align". on line 222
ERROR: Job failed: exit code 1
```

No other changes have been made.

**Comment by DirtyF** [comment]
@kt-ssp sorry for the inconvenience, add this line to your `_sass/minima.scss` :

```sass
$table-text-align: left !default; 
```

**Comment by kt-ssp** [comment]
All good now. Thank you for the prompt response.

**Comment by DirtyF** [comment]
@kt-ssp Thanks for letting us know, this is problematic, we may release a patch to avoid that pain to users.

**Comment by kt-ssp** [comment]
For anyone picking this up in the meantime, the insert position is important. I initially added this to the end, the result was the same. This line has to be inserted before the `@import`.

Mea culpa, should have looked at the committed version here first 😄
