### ISSUE TITLE
gihub-pages minima (2.1.1) couldn't show tables properly

### ISSUE THREAD

**Issue by HackingGate** [jekyll/minima#188]
Table shows properly on local Jekyll server, but not on online server(Hosted by GitHub pages).

I copy-pasted an table example from [kramdown doc](https://kramdown.gettalong.org/syntax.html#tables).

```
|-----------------+------------+-----------------+----------------|
| Default aligned |Left aligned| Center aligned  | Right aligned  |
|-----------------|:-----------|:---------------:|---------------:|
| First body part |Second cell | Third cell      | fourth cell    |
| Second line     |foo         | **strong**      | baz            |
| Third line      |quux        | baz             | bar            |
|-----------------+------------+-----------------+----------------|
| Second body     |            |                 |                |
| 2 line          |            |                 |                |
|=================+============+=================+================|
| Footer row      |            |                 |                |
|-----------------+------------+-----------------+----------------|
```

Works fine on local Jekyll. But online server shows like: 

![table](https://i.imgur.com/7x1gjeJ.png)

I checked my Gemfile

```
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!
gem "jekyll", "~> 3.7.0"

# This is the default theme for new Jekyll sites. You may change this to anythi\
ng you like.
gem "minima", "~> 2.2.0"

# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
# gem "github-pages", group: :jekyll_plugins
```

Then uncommented  `gem "github-pages", group: :jekyll_plugins`, commented `gem "jekyll", "~> 3.7.0"`
After `bundle update` I got  

```
Bundler could not find compatible versions for gem "minima":
  In Gemfile:
    minima (~> 2.2.0)

    github-pages was resolved to 175, which depends on
      minima (= 2.1.1)
```

The gem github-pages (175) is forcing me to use minima (2.1.1). If I change my Gemfile to minima (2.1.1). My local Jekyll server will gets the same situation as online server which couldn't show tables properly.

Is this means that GitHub is using minima (2.1.1) or older when generating pages?

I'm not familiar with Web developing. I just created a new Jekyll project. And didn't modified any .css files.

I think this issue will be solved when github-pages releases a new gem version.

But I don't understand why I can't get table works on minima (2.1.1). 

Is there anyway to solve the problem?

**Comment by ashmaroli** [comment]
> Is this means that GitHub is using minima (2.1.1) or older when generating pages?

Yes. GitHub Pages is still using the older version. Check this link to know what its using: https://pages.github.com/versions/

Is there anyway to solve the problem?

There is.. but it requires a bit of work..

**Comment by DirtyF** [comment]
Should be fixed with latest release.
