### ISSUE TITLE
Ability to specify Pages in Header

### ISSUE THREAD

**Issue by benbalter** [jekyll/minima#19]
It's awesome that the theme auto-includes a list of pages in the header, but once you get above a certain number of pages, it gets a bit unwieldy. 

It also be cool to be able to set the order of the pages. Thinking maybe some sort of array in the config of page paths to include, falling back to all pages if not set.

**Comment by ashmaroli** [comment]
Cool Idea. Though jekyllrb.com uses a similar technique, it would be cool if we could simply load all .md under **/pages** and then using docs.yml to define the top navigation for minima as well.

```yaml
docs:
  - about.md
  - contact-us.md
  - a-random-page.md
  - another-random-page.md
```
and use liquid (not entirely correct) to set the layout:

```html
<ul id="top-nav">
{% for doc in docs %}
<li>
<a href="{{ link_to_doc }}"></a>
</li>
{% endfor %}
</ul>
```

**Comment by benbalter** [comment]
You can do that with something like `site.pages | where:"path", path`.

**Comment by mlovic** [comment]
Strongly in favor of this feature. I'm currently copying `_includes/header.html` from the source into my project and adding 

    {% for my_page in site.pages %}
      {% if my_page.hide_header_link %}{% continue %}{% endif %}

as a workaround. I'd be happy to help out with it.

**Comment by benbalter** [comment]
> I'd be happy to help out with it.

@mlovic if you'd like to to begin a pull request to implement this feature, I'd love to see it as well and would be glad to review it. 😄

**Comment by benbalter** [comment]
Is anyone from @jekyll/ecosystem interested in taking a pass at this?

**Comment by Crunch09** [comment]
@benbalter Hi, i'm not in the ecosystem group (yet) but if no one else has already started on this i would be glad to help out.

**Comment by parkr** [comment]
@Crunch09 you can join via https://teams.jekyllrb.com!

**Comment by parkr** [comment]
@benbalter Do you want this for Minima 2?

**Comment by mohsenSy** [comment]
@benbalter Can you help me please with adding links to top navigation bar, how can I do this?

Thanks a lot.

**Comment by DirtyF** [comment]
@mohsenSy It's explained in the `_config.yml` file: https://github.com/jekyll/minima/blob/affcd93be22e960afd2be08e6891d99b31bcf920/_config.yml#L17-L20

**Comment by su-narthur** [comment]
@DirtyF Looks like that documentation got removed from _config.yml

**Comment by DirtyF** [comment]
This option is documented in the main config file...
https://github.com/jekyll/minima/blob/master/_config.yml#L37-L40

... and in the README:
https://github.com/jekyll/minima#customize-navigation-links
