### ISSUE TITLE
Social icon path should include the baseurl if set

### ISSUE THREAD

**Issue by badmintonkid** [jekyll/minima#197]
It looks like the social icons are hardcoded to /assets/minima-social-icons.svg. However, if the baseurl is set, it needs to be pre-pended to that path, otherwise the svg will not be found.

**Comment by itsjavi** [comment]
any update on this?

**Comment by ashmaroli** [comment]
This looks like a legit bug to me.. Stay tuned for a fix..

**Comment by ashmaroli** [comment]
PR opened.. You guys can test with the PR's branch if interested..
```diff
# Gemfile

- gem "minima", "~>2.0"
+ gem "minima", :git => "https://github.com/ashmaroli/minima.git", :branch => "svg-baseurl"
```

**Comment by badmintonkid** [comment]
The changes look fine, but I unfortunately can not test it because bundler is failing to pull your branch for some reason. Maybe because I have an _includes folder to override some stuff? I'm not that familiar with Ruby, so it's possible I'm just doing something wrong. I can confirm that manually copying your changes works, so thanks for fixing this issue.

**Comment by itsjavi** [comment]
@ashmaroli I can confirm that it works with both `baseurl` and without it 👍  :)
thank you
