### ISSUE TITLE
A better experience for GitHub Enterprise users?

### ISSUE THREAD

**Issue by jglovier** [jekyll/minima#2]
In https://github.com/jekyll/jekyll/issues/4918 a user reported that the theme doesn't work well with Enterprise on account of how it handles linking usernames.

Is there a simple way to improve this (and other parts of the jekyll experience) on GitHub Enterprise?

Opening here for discussion and tracking.

**Comment by benbalter** [comment]
Tracking in https://github.com/jekyll/jekyll-mentions/issues/34.

**Comment by jglovier** [comment]
Closing since it's being tracked in https://github.com/jekyll/jekyll-mentions/issues/34 now.
