### ISSUE TITLE
The page build failed in github.io

### ISSUE THREAD

**Issue by ingmarcosp** [jekyll/minima#20]
I made a push to the repository, but mail me with this:
Your SCSS file `css/main.scss` has an error on line 36: File to import not found or unreadable: minima.

In local I don't have any error...

**Comment by ashmaroli** [comment]
This error is probably because Github Pages is yet to move to Jekyll 3.2
[Reference](https://github.com/blog/2220-github-pages-to-upgrade-to-jekyll-3-2)
