### ISSUE TITLE
Adding of any html file from the minima/_includes directory into the website directory cause the github build to fail

### ISSUE THREAD

**Issue by bishonbopanna** [jekyll/minima#206]
I wanted to override/change certain things in head.html so I copied to over https://github.com/jekyll/minima/blob/master/_includes/head.html to my website directory and built it (jekyll clean + build) - this worked fine in my local but on pushing the same to github the build fails with no particular error. 
Here is my commit that fails in github - https://github.com/bishonbopanna/bishonbopanna.github.io/commit/988bfa422fd4054e0d4a089a4594a3b786434084 

Generic error that i get - 

The page build failed for the `master` branch with the following error:

Page build failed. For more information, see https://help.github.com/articles/troubleshooting-github-pages-builds/.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can contact us by replying to this email.

**Comment by ashmaroli** [comment]
To check if you can reproduce the error locally replace `jekyll` in your Gemfile with the `github-pages-v175` gem
```diff
- gem "jekyll", `~> 3.7"
+ gem "github-pages", "175", :group => :jekyll_plugins
```
and then run:
```bash
$ bundle install && bundle exec jekyll build --trace
```

**Comment by bishonbopanna** [comment]
Thankyou for responding ashmaroli.

Did what you asked and here is the error :

*Liquid Exception: Liquid syntax error
(/git-source/bishonbopanna.github.io/_includes/head.html
<http://bishonbopanna.github.io/_includes/head.html> line 5): Unknown tag
'seo' included in /_layouts/default.html*
*bundler: failed to load command: jekyll (/usr/local/bin/jekyll)*
*Liquid::SyntaxError: Liquid syntax error
(/git-source/bishonbopanna.github.io/_includes/head.html
<http://bishonbopanna.github.io/_includes/head.html> line 5):Unknown tag
'seo' included*

Removed the seo tag and build went fine -
https://github.com/bishonbopanna/bishonbopanna.github.io/commit/6ea3c927c5564ad377c026cfeb1b8d65ef52ef5c

Since the seo tag is part of the
https://github.com/jekyll/minima/blob/master/_includes/head.html, what is
the right fix for this ?

thanks
Bishon

**Comment by ashmaroli** [comment]
The issue is because GitHub Pages is still locked to `minima-2.1.1` and therefore will not load
`jekyll-seo-tag` automatically.. You'll have to include it in your config file:
```yaml
plugins:
  - jekyll-seo-tag
  # other plugins for your site
```

**Comment by bishonbopanna** [comment]
Thankyou Ashwin Maroli. That works perfect.

Side question - I have tweaked minima to have the styling of hacker (dark
theme) - https://bishonbopanna.github.io/  .  I intend to contribute this
back  to minima with an option to choose the darker variant in config
somewhere - any recommendations on how to provide the override and in
contributing to minima in general?

thanks
Bishon

**Comment by ashmaroli** [comment]
> I have tweaked minima to have the styling of hacker (dark theme...). I intend to contribute this
back  to minima with an option...

I checked your live site and IMO, it does not feel like I'm browsing through a dark version of Minima..
I think you're better off shipping your version as a new-entity rather than proposing as a color-scheme-change to Minima.. (mainly because of the change in typography)

I believe this ticket can be closed since the root of your issue lies elsewhere (in the `github-pages` gem..) :smiley:

**Comment by bishonbopanna** [comment]
Agreed. Issue Resolved by adding the below : 

> plugins:
>   - jekyll-seo-tag
>   # other plugins for your site
