### ISSUE TITLE
Use a design system/CSS framework

### ISSUE THREAD

**Issue by DirtyF** [jekyll/minima#212]
We could rely on https://primer.github.io/ to build jekyll's default theme.
Primer comes with some useful modules and would allow us to benefits from robust components.

Another interesting CSS framework: https://tailwindcss.com/

pros:
* benefit from a modular design system/CSS framework
* benefit from a documented style guide and well tested components
* make it easier to customize the theme

cons:
* Introduce a dependency
* too heavy for a minimal theme?

Related issues:
* Introducing a npm dependency
* How to optimize the default stylesheet's weight? (purgeCSS?)
* Updates?

Toughts @jekyll/minima?

**Comment by parkr** [comment]
Our goal with minima was to be _minimal_. We have `jekyll-theme-primer` for those who are interested in using primer as their base. Ideally `minima` would need only maintenance going forward – it does everything we can possibly want a minimal theme to do, and more. I'd rather see us do this kind of work in a `maxima` theme which can have all the bells and whistles that folks like in themes. `minima` should remain as minimal and simplistic as possible.

**Comment by DirtyF** [comment]
@parkr thanks for the reminder.
