### ISSUE TITLE
Cannot get GitHub social link in footer to show

### ISSUE THREAD

**Issue by johnramsden** [jekyll/minima#214]
I'm not sure what I've done wrong, I've added my GitHub username to my [_config.yml](https://github.com/johnramsden/flatpakrepo/blob/master/docs/_config.yml), with `github_username:  "johnramsden"` but it just won't show. I've tried it locally as well as remotely and [this](http://flatpakrepo.johnramsden.ca) is what I end up with.

I've done exactly as I've done on other sites where it's worked, so the only thing I can think of is that I've done something strange in the configuration.

**Comment by ashawley** [comment]
Looks like you're using the theme, but then you have imported the files  of entire repo (or gem), as well.  And the copy of the repo (or gem) that you imported is from before #190 was merged.  So you have the `social_sites` key prefixing everything in `social.html`

https://github.com/johnramsden/flatpakrepo/blob/6331f84/docs/_includes/social.html

**Comment by johnramsden** [comment]
@ashawley Brilliant, thanks! I deleted `social.html` and everything's working. I needed to modify some the files which is why I imported the `_includes`. I guess I just need to delete all files I'm not trying to override.
