### ISSUE TITLE
A file was included in `/_layouts/default.html` that is a symlink or does not exist in your `_includes` directory

### ISSUE THREAD

**Issue by mateuszbuda** [jekyll/minima#215]
My github page, that built successfully over 2 weeks ago, now is failing with the following error:

> The page build failed for the `master` branch with the following error:
> 
> A file was included in `/_layouts/default.html` that is a symlink or does not exist in your `_includes` directory. For more information, see https://help.github.com/articles/page-build-failed-file-is-a-symlink/.
> 
> For information on troubleshooting Jekyll see:
> 
>   https://help.github.com/articles/troubleshooting-jekyll-builds

Could you suggest how to resolve this?
Do I need to update something or add some files?
Is it a bug in minima theme?

**Comment by holgergp** [comment]
I built it locally and following detailed error appeared: 
```
Liquid Exception: Could not locate the included file 'icon-github.html' in any of ["/Users/hgp/development/sideprojects/podcast/autoweird/autoweirdfm.github.io/_includes", "/usr/local/lib/ruby/gems/2.4.0/gems/minima-2.4.0/_includes"]. Ensure it exists in one of those directories and, if it is a symlink, does not point outside your site source. in /_layouts/default.html
jekyll 3.5.0 | Error:  Could not locate the included file 'icon-github.html' in any of ["/Users/hgp/development/sideprojects/podcast/autoweird/autoweirdfm.github.io/_includes", "/usr/local/lib/ruby/gems/2.4.0/gems/minima-2.4.0/_includes"]. Ensure it exists in one of those directories and, if it is a symlink, does not point outside your site source.
~/d/s/p/a/autoweirdfm.github.io git:(master) 2M > bundle exec jekyll serve
```
GH seems to have switched the minima theme to 2.4.0. which does not have an icon-github.html or an icon-twitter.html. Instead an (more convenient) social.html.
I changed it in our template [here](https://github.com/autoweirdfm/autoweirdfm.github.io/commit/9311c32162f9b0fc3ab1c333418e5af3794220a3).
Maybe this helps you. 
I think this should be documented somewhere. Ideas?

**Comment by DirtyF** [comment]
This change was introduced in https://github.com/jekyll/minima/releases/tag/v2.2.0, I added a link to the diff in the update instructions. Thanks for the feedback.

**Comment by holgergp** [comment]
Thanks!

**Comment by wrzasa** [comment]
Thanks. You just let me make our website work again! :D
