### ISSUE TITLE
Another issue with: A file was included in `/_layouts/default.html` that is a symlink or does not exist in your `_includes` directory

### ISSUE THREAD

**Issue by JacobRPrice** [jekyll/minima#220]
Hi everyone, 
I'm another user who ran into a similar problem as @mateuszbuda in issue #215 . Following @holgergp 's  [suggestion](https://github.com/autoweirdfm/autoweirdfm.github.io/commit/9311c32162f9b0fc3ab1c333418e5af3794220a3) , I commented out what I had in "footer.html" and added  

`{% include social.html username=site.github_username %}`

in it's place. My build is still failing and I'm really not sure why. 

I'd appreciate any input you guys may be able to provide. 

Sidenote: The reason I'm using "custom" head/header/footer files is that I want to be able to utilize:    
* a header image
* a footer image
* google analytics
* twitter cards (unique for each post, if needed)    

and I'm not sure if that's possible without specifying them in this manner (I'm very much a newbie at this). 

Thank you in advance. 

Jake

**Comment by ashmaroli** [comment]
@JacobRPrice have you tried running your site locally with the *latest* `github-pages` gem..?
That should point you to the offending template or markup.
Please report back to us **if** the offending *include* doesn't refer to `icon-github.html` or `icon-twitter.html`

@DirtyF @benbalter  any chance you guys could push patch-fix release for both Minima and GitHubPages a.s.a.p..? I believe this issue has already been resolved on `minima:master`

**Comment by ashawley** [comment]
> I commented out what I had in "footer.html"

You used HTML comments.

https://github.com/JacobRPrice/JacobRPrice.github.io/commit/8ce42a2

That's probably not going to be sufficient to keep Jekyll from trying to process includes.

**Comment by ashmaroli** [comment]
@JacobRPrice Also note that the new `social.html` does not need parameters.. simply include.
```
{% include social.html %}
```

**Comment by JacobRPrice** [comment]
@ashawley and @ashmaroli 
A huge thank-you to both of you! 
I deleted the commented out section in footer.html and also removed the parameters from the `{% include social.html %}` line. This fixed the issue right away. 
Thanks again.
Jake
