### ISSUE TITLE
Footer should be at the bottom of the screen

### ISSUE THREAD

**Issue by montyf** [jekyll/minima#222]
For long posts, I have to scroll down to see the footer, and the page ends right after -- there is no unwanted space below the footer. This is good.

For short posts, the footer is right below the post and there is a lot of space below the footer, between it and the end of the screen. This is bad. The footer should be at the bottom of the screen in this case.

For a default theme, there are a lot of style issues... but I am learning a lot about CSS :)

**Comment by montyf** [comment]
I found this adorable little article that explains the issue with an elegance that almost matches mine.

https://cssreset.com/how-to-keep-footer-at-bottom-of-page-with-css/

**Comment by DirtyF** [comment]
This can be done via Flexbox: https://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer/
