### ISSUE TITLE
RSS Feed is broken

### ISSUE THREAD

**Issue by phamhieu** [jekyll/minima#227]
I recently deploy a Gihub Pages with minima theme. Everything works perfect except the RSS Feed.
Click on "subscribe via RSS" will show an 404 page. 
I also check minima demo page. The feed is broken also.

<img width="397" alt="screen shot 2018-04-10 at 3 42 55 pm" src="https://user-images.githubusercontent.com/689843/38542984-e5cafc10-3cd5-11e8-998c-aa3c59961242.png">

**Comment by DirtyF** [comment]
@phamhieu Sorry for that, minima use `jekyll-feed` plugin to generate the feed, make sure you declare the plugin in your config file:

```
plugins:
  - jekyll-feed
```

Please confirm it fixes this issue, thanks.

**Comment by phamhieu** [comment]
Yes, adding `jekyll-feed` into **_config.yml** file fixes the RSS Feed. Thanks @DirtyF
