### ISSUE TITLE
Can I set excerpt word length?

### ISSUE THREAD

**Issue by binlidaily** [jekyll/minima#230]
I want the post excerpt have the same length, so I have tried to change the setting in `home.html` like this:

```
{%- if site.show_excerpts -%}
  {{ post.excerpt | strip_html | xml_escape | truncatewords: site.excerpt_length}}
  {% assign excerpt_word_count = post.excerpt | number_of_words %}
  {% if post.content != post.excerpt or excerpt_word_count > site.excerpt_length %}
    ……<a href="{{ post.url | prepend: site.baseurl }}" class="post-read-more">[Read&nbsp;More]</a>
  {% endif %}
{%- endif -%}
```
and I set the excerpt_length in `_config.yml`

But the word length of excerpt in home page is not changed.

I am confused about this, I don't know how to set it, could you please do me a favor, thank you so much.

**Comment by ashmaroli** [comment]
*One way to get it done is by using the [`truncate`](https://shopify.github.io/liquid/filters/truncate/) filter*
```
{%- if site.show_excerpts -%}
  {{ post.excerpt | truncate: site.excerpt_length | default: 100 }}
{%- endif -%}
```
The above example truncates excerpts to **100 characters (inclusive of 3 char ellipsis)** by default and can be configured to about **80 chars** by having **`excerpt_length: 80`** defined in your `_config.yml`.

*Disclaimer: The example is untested and therefore prone to errors. However, it should be a great starting point for simple, straight-forward excerpts (esp. those that do not contain additional Liquid Tags..)*
