### ISSUE TITLE
Can I change the order of the button in the header?

### ISSUE THREAD

**Issue by binlidaily** [jekyll/minima#231]
As you can see in the picture below, the `About` button is the first one. However, I think I use the `Category` and `Tag` button more frequently, so I want to put the `About`  last. I find that I just put some markdown file or html file in the root directory, there would be corresponding button in the header. I cannot find the place to change the order, Any advise or guidance would be greatly appreciated, thank you so much! 

![image](https://user-images.githubusercontent.com/5987437/38774076-8679103e-4091-11e8-8d2c-85e12f1b2ce5.png)

**Comment by de4ce** [comment]
https://github.com/jekyll/minima#customize-navigation-links

**Comment by binlidaily** [comment]
Thank you so much! My apology. I haven't see the `README` in the project carefully. Thank you for your answer.
