### ISSUE TITLE
Request to add Letterboxd to social networks

### ISSUE THREAD

**Issue by adamtyoung** [jekyll/minima#238]
Love the theme--it would be awesome if Letterboxd (http://letterboxd.com) was included in the social list for film-buffs. Otherwise, I give minima five bags of popcorn. Cheers!

**Comment by DirtyF** [comment]
Thanks for the suggestion, but we can't list all social networks out there, so we'll limit ourselves to the most commonly used.

Feel free to override the [`social` include](https://github.com/jekyll/minima/blob/master/_includes/social.html) in your repo.
