### ISSUE TITLE
Overrides On GitHub Pages For Some _includes Files Works Goofy

### ISSUE THREAD

**Issue by ng-chicago** [jekyll/minima#240]
It's weird, I don't know why
If you want to override the (_includes/icon-github.html)  file, that works as expected locally, but not on GitHub Pages after you push

If you want to make that work on GitHub Pages, you need to include the parent file (footer.html) in your local _includes folder. Even if you are changing nothing in that file.

If anyone knows why I would be interested to know the explanation.

**Comment by ashawley** [comment]
What version of GitHub pages?

**Comment by ng-chicago** [comment]
Not sure where I check that
Just set it up today, so the most recent?
https://github.com/ng-chicago/ng-chicago.github.io

**Comment by ng-chicago** [comment]
Not sure what that means, but I'll investigate - thanks
Note:
The override DOES work on GitHub only if I include the parent file (footer.html) in my local _includes

**Comment by ashawley** [comment]
I'm wondering if you may be experiencing an issue from a more recent version of `github-pages` (v178 requires minima 2.4.0) when the social includes were changed in minima #141, but then decided to allow the old ones to work in #217 that was included in v182 (and minima 2.4.1).

**Comment by ng-chicago** [comment]
Looks like it was my issue
An old version of ruby on my machine was causing bundle update errors I did not catch
upgraded to 2.5.1
GitHub-pages (183)
Also now using minima-2.4.1

Thanks for the help Aaron!
