### ISSUE TITLE
tables can create horizontal overflow on mobile

### ISSUE THREAD

**Issue by decathorpe** [jekyll/minima#243]
This makes some of my posts look (and behave, because of the possible horizontal scrolling) badly on mobile.

Example: https://decathorpe.com/2018/04/08/this-week-in-fedora-2018w14.html

Zooming out to see the whole page at once looks even worse.

First image: Top of one of my posts (table not fully visible)

![1](https://user-images.githubusercontent.com/12836693/39872002-e7585642-5466-11e8-99ce-da8e2b7aa4a6.png)

Second image: Scrolled to the right (rest of table visible, but all other styling is off, for example the top bar and navigation menu)

![2](https://user-images.githubusercontent.com/12836693/39872006-ea7c2fc4-5466-11e8-837b-d409b5240a4d.png)

**Comment by M0nica** [comment]
Would any of these responsive table implementations be ideal? A scrollbar appears for the entire table on smaller screens.
[http://maxdesign.com.au/articles/simple-responsive-table/](http://maxdesign.com.au/articles/simple-responsive-table/ )

**Comment by DirtyF** [comment]
@M0nica That's what we do on jekyllrb.com, care to submit a fix?

**Comment by M0nica** [comment]
Sure @DirtyF I will work on this.

**Comment by M0nica** [comment]
I submitted a pull request [https://github.com/jekyll/minima/pull/246](https://github.com/jekyll/minima/pull/246) however, I believe this change can only be implemented if tables are updated to be HTML based instead of Markdown-based. That is how the Jekyll site approaches this.

**Comment by decathorpe** [comment]
Hm. I just noticed that over-wide code blocks *do* have the scrollable behavior I am looking for. Would it be possible to do the same thing for tables?
