### ISSUE TITLE
Deep url for youtube

### ISSUE THREAD

**Issue by kkimdev** [jekyll/minima#251]
Hi, I'm creating a personal blog with minima and I noticed I can't specify my youtube channel link:

https://www.youtube.com/channel/UCFjh-t8vgQxkxAvhOd1byzw

I needed to specify `channel/UCFjh-t8vgQxkxAvhOd1byzw ` as id but `/` is escaped in the produced html.  On web, it was still able to open the correct channel but on Android with Youtube app redirection, it directs to a wrong channel.

How about introducing `youtube_url` variable and fallback if youtube username is not specified?

**Comment by ashawley** [comment]
Unfortunately, Youtube has like 3 ways to link to user accounts:

> ID-based URL
> Example: youtube.com/channel/UCUZHFZ9jIKrLroW8LcyJEQQ

> Custom URL
> Example: youtube.com/c/YouTubeCreators

> Legacy username URL
> Example: youtube.com/user/partnersupport

https://support.google.com/youtube/answer/6180214

**Comment by DirtyF** [comment]
As we don't know which one is commonly used , you'll have to override the theme.

**Comment by kkimdev** [comment]
Youtube no longer supports http://www.youtube.com/username url, which is the current minima default scheme.

Also, to apply custom URL, the channel needs to have at least 100 subscribers https://support.google.com/youtube/answer/2657968?hl=en

So I think it makes more sense to have `youtube_url`, as there is no sensible default.  Otherwise, it's effectively forcing people to override the theme whenever they want to put Youtube URL.

**Comment by DirtyF** [comment]
`https://youtube.com/<username>` redirects to `https://www.youtube.com/user/<username>` so we're still 👌, we could at least avoid the redirection though.

**Comment by pathawks** [comment]
The problem is that `https://youtube.com/UCFjh-t8vgQxkxAvhOd1byzw` does not redirect to `
https://www.youtube.com/channel/UCFjh-t8vgQxkxAvhOd1byzw`, but instead is just a 404.

**Comment by kkimdev** [comment]
Clarification: https://youtube.com/<username> and https://www.youtube.com/user/<username> are no longer supported, i.e., new Youtube accounts can't have those URLs.  Only accounts already had those URLs before Youtube deprecated can keep them.

**Comment by ashawley** [comment]
What about keeping `youtube_username` as is, but adding `youtube_channel`?  The channel would be appended to _youtube.com/channel/\<channelname\>_ to get the link.

**Comment by ashawley** [comment]
Channels are just arbitrary letters and numbers, so the Youtube icon shouldn't have the channel name text alongside it?

**Comment by kkimdev** [comment]
Yeah it will be pointless to display the raw channel ID.  Though I think people might want to display their channel name, if they have.  Personally I'm fine with either ways for my blog.
