### ISSUE TITLE
Why assets/main.scss is in the directory of assets, instead of _sass/main.scss?

### ISSUE THREAD

**Issue by BoQsc** [jekyll/minima#269]

**Comment by DirtyF** [comment]
Because Jekyll does not copy folders beginning with an underscore in the output directory.

**Comment by BoQsc** [comment]
@DirtyF 
Could you explain it in more verbose way or at least give me link related to this topic of "output directory" and how exactly Jekyll works in the context of GitHub Pages. 
The answer got me confused even more. 😦

**Comment by DirtyF** [comment]
See https://jekyllrb.com/docs/assets/#sassscss
