### ISSUE TITLE
Wouldn't it be logical to put /_sass/ folder inside /_includes/ folder?

### ISSUE THREAD

**Issue by BoQsc** [jekyll/minima#275]
Files in **/_sass/** are considered partials for **/assets/main.scss** that later generate **/assets/main.css**
to be used by .html files of **/_layouts/** 
Therefore  **/assets/main.scss** file and **/_sass/** folder are partials that generates **main.css** that is partial for the **/_layouts/**.

The final result should look like this: 
Moving **_sass** folder into **_includes/_sass/**
that would be used by **/assets/main.scss** to generate **/assets/main.css**

**Comment by DirtyF** [comment]
Minima will continue to adopt [Jekyll's default behaviour with Sass files](https://jekyllrb.com/docs/assets/#sassscss). You could put Sass files in `_includes` folder, and/or you could configure _sass_dir_ if you wish, that's up to you.
