### ISSUE TITLE
The home layout HTML error

### ISSUE THREAD

**Issue by ettingshausen** [jekyll/minima#279]
https://github.com/jekyll/minima/blob/280deb6d21f9d91f29af928b9134d8b78f05046e/_layouts/home.html#L31 
It should be like this: `<a href='{{ "/feed.xml" | relative_url }}'>via RSS</a>`

**Comment by ashmaroli** [comment]
@ettingshausen you're welcome to submit a PR that does the opposite of your suggestion:
```html
<a href="{{ '/feed.xml' | relative_url }}">via RSS</a>
```

**Comment by ettingshausen** [comment]
Thank you  @ashmaroli 
PR #280
