### ISSUE TITLE
[Question] Release of new minima version

### ISSUE THREAD

**Issue by ArazAbishov** [jekyll/minima#28]
Hi devs,

Thanks a bunch for awesome work which you are doing! I just wanted to ask when are you planning to release new version of theme? Looking forward to disqus support in minima!

Cheers.

**Comment by proehlen** [comment]
@ArazAbishov Is it not supported yet?  I got the impression from the README that it was already supported. Have been trying to get it to work for the last hour with no luck but I don't know what I'm doing.

**Comment by ArazAbishov** [comment]
@proehlen Latest version of minima available as a theme is 1.0.1 (which was released before disqus support implementation).

**Comment by proehlen** [comment]
@arazabishov OK, thanks very much for the explanation.

**Comment by benbalter** [comment]
Once https://github.com/jekyll/minima/pull/31 gets merged, we should be able to release `v1.1.0`.

**Comment by ArazAbishov** [comment]
@benbalter Cool! Looking forward to updates.

**Comment by benbalter** [comment]
https://github.com/jekyll/minima/releases/tag/v1.1.0 is out. 😄

**Comment by ArazAbishov** [comment]
Awesome, thanks a lot!
