### ISSUE TITLE
Footer broken after v2.1.1

### ISSUE THREAD

**Issue by letmutx** [jekyll/minima#282]
I have a blog which uses minima which had footer broken when upgrading from 2.1.1 to any newer release. By experimenting, I found that the issue is because of 16d205f404576adf437437748404411758f66bbd After reverting `vertical-align` to `middle`, I could get the footer social icons to align properly. See the screenshot below for a quick preview. 

To reproduce, clone my [site](https://github.com/letmutx/letmutx.github.io) and check out to `7a33724f336bfe38172c236200c02d389d1f70af`. However, I couldn't reproduce the issue with the sample blog by running `scripts/server`.

If this is not a bug, please close the issue. Thanks for the awesome theme.

![rsz_blog-bug](https://user-images.githubusercontent.com/26674948/45732399-bef86200-bbf9-11e8-82b4-4bac5c155b0e.png)

**Comment by DirtyF** [comment]
Looks like you tried to override sass files and somehow messed up with the sass files, if you remove the `_sass` folder and default to minima, display is fine.
