### ISSUE TITLE
Document how to overwrite default templates

### ISSUE THREAD

**Issue by dret** [jekyll/minima#30]
it seems that due to the new packaging, now the previously available files in _includes and _layouts are not available anymore. some guidance somewhere suggested to create these directories and place modified copies in there, if you want to change anything.
the problem with this is that for this to work, you would need to have access to the originals so that you can copy and change them. i tried to locate them, but couldn't find them in my newly installed jekyll site.
https://github.com/dret/RegMan is the site that i generated and that is missing the layouts and includes.
https://github.com/dret/webconcepts is one i set up recently which still had the directories, and thus was much easier to customize.
how is the new process to customize the minima theme? it's not as easy as it used to be (just change the files in your site directory), so a bit of documentation would be very helpful.

**Comment by benbalter** [comment]
@dret see http://jekyllrb.com/docs/themes/#overriding-theme-defaults, although that's admittedly not complete. If there are any files you'd like to override, you should copy the files from this repository into your site. I'm going to leave this issue open to track documenting that better.

**Comment by DirtyF** [comment]
@dret to locate the theme file on your system you can use bundle info <gem>:

```
$ bundle show minima
/Users/frank/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/minima-1.0.1
```

You can also clone the theme repository outside jekyll's root folder and copy the files as suggested above:

`git clone https://github.com/jekyll/minima.git`

@benbalter shall we add this to the documentation ?

**Comment by benbalter** [comment]
>  shall we add this to the documentation ?

I think so.

**Comment by dret** [comment]
On 2016-09-06 06:41, Ben Balter wrote:
> @dret <https://github.com/dret> see
> http://jekyllrb.com/docs/themes/#overriding-theme-defaults, although
> that's admittedly not complete. If there are any files you'd like to
> override, you should copy the files from this repository into your site.

that seems odd, since i would be overriding my local files (that have 
some version and behavior) with possibly updated files (which may have 
other versions and behaviors). i may be a bit too traditional here, but 
for my taste all of this is way too opaque and mysterious. i liked 
seeing the files and being able to update them much better.

**Comment by dret** [comment]
On 2016-09-06 07:59, Frank Taillandier wrote:
> @dret <https://github.com/dret> to locate the theme file on your system
> you can use bundle info :
> |$ bundle show minima
> /Users/frank/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/minima-1.0.1 |

this is much better than the repo way because i can at least get access 
to the files that are actually used, and not some possibly different 
version in the github repo.

> @benbalter <https://github.com/benbalter> shall we add this to the
> documentation ?

if you do, i think it would be better to document the way how to find 
the files that are being used (the one in the gem).

**Comment by DirtyF** [comment]
@dret done in #5335, thanks for the feedback.
