### ISSUE TITLE
Add Wikipedia Page as an option link in the footer

### ISSUE THREAD

**Issue by karipov** [jekyll/minima#310]
Hello,

Would it be possible to add a new option to link a wikipedia page through a simple addition of the parameter in the _config.yml?

**Comment by ashawley** [comment]
Would the English Wikipedia be sufficient?

**Comment by DirtyF** [comment]
That social icons are starting to become a burden, we should come with a better solution to allow users to add their favorite service, I'm thinking of removing all current icons alltogether in next major version.

**Comment by ashawley** [comment]
Probably more appropriate to propose and discuss in a new ticket separate from this one.

**Comment by DirtyF** [comment]
@ashawley I might actually close this one for this very reason.

**Comment by ashawley** [comment]
Social icons were a new feature as of only this year.  I'm sure it will stabilize as time goes on and hopefully become less of a burden.  SVG seems like the major pain point, but I may not know what you know.

With respect to requests for more services, it may help to have a popularity threshold for addition.  I suggested as such in #265 by using Alexa.  

It would also be nicer to be to more self-service. Someone suggested using Font Awesome for icons in the beginning and it got vetoed.

PS.  We can all agree Google+ will be dropped soon. :-)

**Comment by DirtyF** [comment]
If people want to add social icons, they should override the theme. We should ship for at least 80% of users, and rightnow nobody will use _every_ social network listed in the config. We already have accepted too much. You can't make everyone happy, and as maintainers we have to learn also to say no.
