### ISSUE TITLE
Adding a horizontal rule under heading

### ISSUE THREAD

**Issue by davxiao** [jekyll/minima#317]
Is there a way to add nice and subtle horizontal rule with the same look and feel of what GitHub md has? 
I tried adding `-------------` under the heading line obviously it doesn't work out.
Also tried adding `<hr>` it works but the look and feel is really different from GitHub.  

<img width="832" alt="screen shot 2018-12-02 at 7 17 23 pm" src="https://user-images.githubusercontent.com/3964699/49346914-f27a5280-f666-11e8-95e0-e4a5fbc01d6d.png">

**Comment by DirtyF** [comment]
See https://github.com/jekyll/minima#customization
Add `border-bottom: 1px #e1e4e8 solid` to the heading you're targeting.
