### ISSUE TITLE
JSONFeed Support.

### ISSUE THREAD

**Issue by derpmarine168** [jekyll/minima#328]
Please add suport for [JSONFeed](https://jsonfeed.org/). A simple file, like [this](https://gist.github.com/derpmarine168/0b2c52cd38e9333b80cade9f7b1f6a74) that I'm using in my website, should do the trick.

**Comment by derpmarine168** [comment]
Why?

**Comment by DirtyF** [comment]
see https://github.com/jekyll/jekyll-feed/issues/172

**Comment by derpmarine168** [comment]
Yes, having it as a template is a first choice solution, idealy it would be done in ruby and then serialized to JSON to avoid errors that will cause the parser to fail. It's quick and easy fix for a simple problem though.
That issue went stale a year ago and JSONFeed is commonly used anyway, and a one-size-fits-all theme and should support as many use cases as practial, for both authors and consumers, I think.

**Comment by DirtyF** [comment]
>  a one-size-fits-all theme and should support as many use cases as practial, for both authors and consumers

minima aims to be _minimal_, it's only a basic jekyll starter theme to start blogging, not a multi-purpose theme for advanced users.

**Comment by derpmarine168** [comment]
Ok. you should probably fix this then:
![bf4dcdf0-5657-4cb0-af58-0238c95bf8a4](https://user-images.githubusercontent.com/28905212/50424469-46d6b380-085c-11e9-968e-9df764d9ed4c.jpeg)
PS. JSONfeed was meant to be simpler than RSS. That’s basicaly it’s whole appeal - no more XML hell.
