### ISSUE TITLE
Using Tensorflow JS with Minima

### ISSUE THREAD

**Issue by amitrege** [jekyll/minima#341]
Hello all,
I was wondering if there is a way to use Tensorflow JS with Minima. In theory, it seems possible (I need to add an HTML page basically). However, I'm not quite sure how I could add an HTML page to an existing setup. Any thoughts?

**Comment by ashmaroli** [comment]
@amitrege Please post queries regarding "How to..?" in Jekyll's forum at https://talk.jekyllrb.com/
The GitHub Issues is for reporting bugs and discussions related to developing Minima.
Thanks
