### ISSUE TITLE
Missing "social-links" CSS class

### ISSUE THREAD

**Issue by MadSoftwareScientist** [jekyll/minima#358]
Thanks for the super neat theme!

It seems that footer's style is "behaving funny". In footer.html is used `social-links` class that I'm not able to find from style files.

```
<div class="social-links">
   {%- include social.html -%}
</div>
```

Am I missing something or is the footer style broken?

It seems that commit 28d28332cdf46b7e0f37c94d2a85ad1d23c1f82b caused this (@ashmaroli).

Cheers!

**Comment by ashmaroli** [comment]
@MadSoftwareScientist The `master` contains unreleased changes. If you forked the entire repository, checkout the latest stable branch:
```bash
git checkout 2.5-stable
```

**Comment by MadSoftwareScientist** [comment]
I see. My bad. Thanks!
