### ISSUE TITLE
Something Missing?

### ISSUE THREAD

**Issue by rontarrant** [jekyll/minima#380]
In the instructions, it says:

   And add this line to your Jekyll site:

     theme: minima

How? Is this line added to a file that's on the site? Which file? If not a file, what exactly does this mean?

**Comment by ashmaroli** [comment]
@rontarrant Thank you for reporting this.
The instructions should actually say: *Add this line to your config file..*
I'll push a correction shortly.

**Comment by rontarrant** [comment]
Thanks for the prompt response, Frank, but now I have another question...

Are you talking about _config.yml? I'm sure this seems obvious to you, but
I don't know Ruby Jekyll or any of her friends.

**Comment by ashmaroli** [comment]
@rontarrant Perhaps, it'd be easier ahead if you acquaint yourself with Jekyll and its Universe. The best way would be to read through [the official docs](https://jekyllrb.com/docs/).

**Comment by rontarrant** [comment]
Yeah, I tried that. Thanks anyway.
