### ISSUE TITLE
Social Media Icons / Links

### ISSUE THREAD

**Issue by rudolfovic** [jekyll/minima#39]
The footer templates comes with only two links (github and twitter). It would be nice to generalise and this should not be too hard to do. One way is Font Awesome which supports almost every conceivable icon. A subset of these could be added or this could probably be done dynamically too.

Currently, SVGs are used instead, so creating more of these would actually require effort (unless these were actually just borrowed from somewhere). On the other hand, abandoning SVG in favour of FA or another solution may lead to backward compatibility problems. The only one I can think of is the discrepancy in appearance unless this is actually done dynamically. Then it is also important to avoid duplicating github and twitter links.

I am not too sure if backward compatibility is actually important in this case, especially given that both github and twitter have identical names in FA.

Finally, all of this can obviously be overridden or solved by another theme but hardcoding these two links does not seem like a favourable or a necessary solution.

P.S. I read all other open issues to make sure I am doing this correctly and suitably but nevertheless this is my first github issue (in fact this is my first real public mark on github) so please react appropriately 😇

**Comment by ward** [comment]
To chime in, I am not a fan of seeing font awesome added as a dependency for this minima(l) theme.

**Comment by david-gang** [comment]
I agree with @rudolfovic . I would also like to have an easy way to add a linkedin account to my footer

**Comment by pathawks** [comment]
Sounds like a great issue for a plugin to remedy :+1:

I can imagine users of many themes wanting to include a similar list of social media links. Rather that each theme solving the problem individually, maybe a plugin could handle most of the heavy lifting, with themes just adding a small bit of CSS for custom styling.

**Comment by domingohui** [comment]
As suggested by @david-gang, I made a PR #112. Please feel free to take a look at it!

**Comment by DirtyF** [comment]
closing this in favor of #141 .
