### ISSUE TITLE
Apostrophe has a space after it?

### ISSUE THREAD

**Issue by p2635** [jekyll/minima#391]
When I write up a post in Markdown then view it live, it shows the apostrophe with an extra space for some reason? See page: https://pwong.co.uk/learning/languages/2019/07/22/dict-friend-or-foe.html.

![image](https://user-images.githubusercontent.com/4522927/62009638-666aed00-b159-11e9-92f1-376ec082d8af.png)

Is this due to the way my system is set up or is it the font that I'm using for the css? When I view it on my phone, it seems fine. Let me know if you need more info.

**Comment by ashmaroli** [comment]
It could be your font. Inspect it using your browser's debugging tool and find out which font is being used and that if disabling the `font-family`'s `"kern"` property helps..

**Comment by p2635** [comment]
Thanks @ashmaroli , I found out it's just my the default font in my OS settings (Noto Sans CJK HK). 
![image](https://user-images.githubusercontent.com/4522927/62009942-7b954b00-b15c-11e9-8927-7c07bb367bd8.png)

Not sure there's a whole lot I can do about it to be honest, I think it will be fine on other people's machines (I assume it's just me). I'll just close this for now.
