### ISSUE TITLE
header_pages not working

### ISSUE THREAD

**Issue by warrenalphonso** [jekyll/minima#393]
I'm trying to reorder my pages. I haven't changed the permalinks for any of them. My current _config.yml file looks like 
`theme: minima 

show_excerpts: true

header_pages: 
  - index.md
  - qc.md 
  - courses.md`

The order is still courses, home, qc. Removing files from header_pages doesn't remove them from the nav bar either.

**Comment by alexddhuang** [comment]
Are you sure you have rebuilt your website after modifying the `_config.yml` file?

**Comment by warrenalphonso** [comment]
Oh wow I'm sorry. So whenever I modify _config.yml, I have to redo jekyll serve. Thank you for the quick reply!
