### ISSUE TITLE
HTML code generated to include a SVG is broken

### ISSUE THREAD

**Issue by oncleben31** [jekyll/minima#40]
# Expected Behavior
I'm trying to add a SVG image from [creativecommons.org](http://mirrors.creativecommons.org/presskit/buttons/88x31/svg/by-nc-sa.svg). I want to have this SVG image inserted with a link to the website.

# Current Behavior
The HTML code generated by jekyll adds 2 tags at the wrong place (`</a></p>`) and break the HTML code consistency: a `</a>` appear and the link doesn't work.
![svg_bug](https://cloud.githubusercontent.com/assets/93244/18618116/02e7062e-7de0-11e6-9bfa-db437da46025.jpg)
![test_bug_svg_html_ __users_administrateur_dev_oncleben31cc-vm_my-blog](https://cloud.githubusercontent.com/assets/93244/18618220/7fcad844-7de2-11e6-8aeb-3f2698e9b693.jpg)

# Possible Solution
Don't know. I'm new to Jekyll. Perhaps it's my bad, perhaps it's the SVG, perhaps a bug related to minima template, or perhaps it's the HTML generator used by Jekyll.

# Steps to reproduce
*   Download the [svg file](http://mirrors.creativecommons.org/presskit/buttons/88x31/svg/by-nc-sa.svg) in `_includes` folder
*   create a snippet `icon-cc-by-nc-sa_bug.html` in the `_includes`folder with following code:
```html
<a href="https://creativecommons.org/licenses/by-nc-sa/3.0/fr/">{% include by-nc-sa.svg %}</a>
````
*   create a post with the following code:
```markdown
---
layout: post
title:  "Test du bug SVG"
date:   2016-09-18 00:12:00 +0000
categories: bug
---
{% include icon-cc-by-nc-sa_bug.html %}
```
*   build with jekyll

# Your environment
```yaml
GEM
  remote: https://rubygems.org/
  specs:
    colorator (1.1.0)
    ffi (1.9.14)
    forwardable-extended (2.6.0)
    jekyll (3.2.1)
      colorator (~> 1.0)
      jekyll-sass-converter (~> 1.0)
      jekyll-watch (~> 1.1)
      kramdown (~> 1.3)
      liquid (~> 3.0)
      mercenary (~> 0.3.3)
      pathutil (~> 0.9)
      rouge (~> 1.7)
      safe_yaml (~> 1.0)
    jekyll-sass-converter (1.4.0)
      sass (~> 3.4)
    jekyll-watch (1.5.0)
      listen (~> 3.0, < 3.1)
    kramdown (1.12.0)
    liquid (3.0.6)
    listen (3.0.8)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    mercenary (0.3.6)
    minima (1.2.0)
    pathutil (0.14.0)
      forwardable-extended (~> 2.6)
    rb-fsevent (0.9.7)
    rb-inotify (0.9.7)
      ffi (>= 0.5.0)
    rouge (1.11.1)
    safe_yaml (1.0.4)
    sass (3.4.22)

PLATFORMS
  ruby

DEPENDENCIES
  jekyll (= 3.2.1)
  minima

RUBY VERSION
   ruby 2.3.1p112

BUNDLED WITH
   1.13.0
```

**Comment by ashmaroli** [comment]
This issue is not due to bug in minima. You made a mistake while pasting the svg code. Please recheck your html file. If you cant resolve it, simply redo adding the SVG on a fresh copy of the html file.

**Comment by ashmaroli** [comment]
This issue is not due to a bug in minima. The SVG file contains unnecessary data embedded by Inkscape. You can remove that data using svg cleaner tools. One such tool online is [kraken.io](https://kraken.io/web-interface)

**Comment by oncleben31** [comment]
thanks for the reply, I found this workaroud in the mean time. Question now: Is it normal and we close the issue or do I assign it to jekyll or perhaps a module used for the html generation?

**Comment by ashmaroli** [comment]
you can close this issue as its not related to *minima*. Regarding, the second part of your question, I'll ping @pathawks.

**Comment by pathawks** [comment]
@oncelben31 Yeah, this seems to be a Jekyll issue.

If you open an issue over there and mention me, I will look into it.

**Comment by oncleben31** [comment]
transfered to https://github.com/jekyll/jekyll/issues/5438
