### ISSUE TITLE
I can't override _layouts/head.html

### ISSUE THREAD

**Issue by mfidemraizer** [jekyll/minima#413]
Hi!

I've copy-pasted `head.html` into `<site name>/_layouts/head.thml`. While content is regenerated when I edit this file, its content isn't rendered into the generated site.

`default.html`, and other layouts have no issue and I can't customize them.

I can't figure out what's going on.

Thank you in advance.

**Comment by ashmaroli** [comment]
@mfidemraizer Ensure that `head.html` is actually a layout in your theme. In Minima, `head.html` is *an include* that needs to be at `<site name>/_includes/head.html`

As an aside, please note that this repo's Issues platform is only for bugs and feature-requests. For support, please use the forum at https://talk.jekyllrb.com/
