### ISSUE TITLE
Medium icon

### ISSUE THREAD

**Issue by tailot** [jekyll/minima#417]
Hi, Could you add the medium icon ?
You can find a reduced path here: https://gist.github.com/tailot/3ccd92107b3416416efa7820e4cf141e

**Comment by DirtyF** [comment]
Sorry, we don't intend to support Mediaum. 
Feel free to[ ovverride the theme](https://jekyllrb.com/docs/themes/#overriding-theme-defaults) to adapt it to your needs.
