### ISSUE TITLE
The `linenos` option for code highlighting seems not working nicely?

### ISSUE THREAD

**Issue by liufuyang** [jekyll/minima#418]
It seems looks like this out of the box?

```
{% highlight golang linenos %}
listener, err = net.Listen(...)
// handle err
for {
    conn, err := listener.Accept()
    // handle err

    // spawn goroutine:
    go handler(conn)
}
{% endhighlight %}
```
Looks like:
![image](https://user-images.githubusercontent.com/161689/68551139-00555d80-040a-11ea-801c-9abe864368b7.png)

Without `linenos` looks like:

![image](https://user-images.githubusercontent.com/161689/68551176-52967e80-040a-11ea-94fc-92d35c78c8d5.png)

**Comment by liufuyang** [comment]
@ashmaroli First is the position shifted to the middle after using `linenos`. Without it you can see in the second pic the code is on the left side of the page. Second is the code area also looks bigger when using it. 

So in my post it looks like this if you put code with line numbers and without line numbers: (the same look on github page as well you can see an example here: http://liufuyang.github.io/2016/02/13/helloworld.html)
![image](https://user-images.githubusercontent.com/161689/68592854-540c8900-0494-11ea-92c0-5dea3352be10.png)

Don't you think that looks ugly?

**Comment by ashmaroli** [comment]
@liufuyang What I'm saying is, you need to edit your site's CSS to *adjust the look and feel*. Jekyll doesn't alter your CSS.

**Comment by liufuyang** [comment]
@ashmaroli I see your point. I have very limited knowledge on CSS editing. Do you by chance know where I can find some guide on how to edit it to make it look nice?

Basically I just used `jekyll` to create an new project and out of the box it looked like that. I didn't change or add any CSS and in the repo I don't see any CSS I could change either.  I have been trying with multiple suggestion I could find on line such as http://sangsoonam.github.io/2019/01/20/syntax-highlighting-in-jekyll.html but it all didn't work for me.

**Comment by ashmaroli** [comment]
@liufuyang To reset the styling for just that one aspect, add the following to the very end of the `css/main.scss` file in your site's **source** directory.

```css
.rouge-table {
  margin: 0;
  border-collapse: collapse;
  border-spacing: 0;

  pre, code {
    border: none;
  }
}
```

**Comment by liufuyang** [comment]
Thank you very much @ashmaroli, that worked :D
