### ISSUE TITLE
how can I change the skin?

### ISSUE THREAD

**Issue by thephet** [jekyll/minima#420]
I am following what's described in the repo website, but I am getting no results. I am adding to my _config.yml file, just after "theme:minima" "minima: skin:sunrise" (with new line in between as in https://github.com/jekyll/minima#skins) but nothing happens.

Some of the files the text speaks about, like _sass/minima-classic.scss or _sass/minima-sunrise.scss and nowhere to be seen.

Sorry if this is a dumb question, because I am just starting with jekyll.

**Comment by ashmaroli** [comment]
@thephet The skins are part of the unreleased Minima 3.0
You're probably using Minima 2.5.1 (the latest release). The documentation for that is at https://github.com/jekyll/minima/tree/v2.5.1

**Comment by thephet** [comment]
I see. Thank you very much. It was driving me crazy. Indeed I am using 2.5.1, that's the one that got installed by default. Do you suggest I use 3.0? and if so, how can I do it?

**Comment by ashmaroli** [comment]
Like I said, Minima 3.0 hasn't been released yet. Since you're just starting with Jekyll, I wouldn't recommend using an unreleased major version of a theme (the source code isn't stable)

**Comment by thephet** [comment]
Thank you very much

**Comment by gaetgu** [comment]
How would you use 3.0 instead of 2.5? I am currently using 2.5 and having the same issue as you. If anyone knows how to switch that would be great. Thanks! @thephet @ashmaroli

**Comment by hszhakka** [comment]
In fact, you don't have to wait for the release of 3.0. You can directly use the master branch of Minima by using `jekyll-remote-theme`. [Here](https://hszhakka.github.io/2020/01/20/launch-my-blog.html) are my steps, hope that is useful for you.
