### ISSUE TITLE
Upgrade GA from analytics.js to gtag.js.

### ISSUE THREAD

**Issue by tamas-ferenci** [jekyll/minima#421]
I believe that the Google Analytics tracking code should be updated from the `analytics.js` solution to the `gtag.js` way, as it was done [here](https://github.com/pages-themes/cayman/blob/master/_layouts/default.html).

**Comment by DirtyF** [comment]
This was done in https://github.com/jekyll/minima/pull/281

**Comment by tamas-ferenci** [comment]
Thanks for the quick response @DirtyF ! That's interesting, because I see what you mean, yet, Github Pages with this template seems to use old solution for some reason ([example](https://tamas-ferenci.github.io/)).

**Comment by ashmaroli** [comment]
@tamas-ferenci The reason why GHP is still using the old version is because the change has not been shipped yet. It will be included in Minima 3.0, the release date of which is still undecided..

**Comment by tamas-ferenci** [comment]
Thanks @ashmaroli ! I actually thought of this possibility, but then I checked that `minima` was upgraded more than a year ago, so I thought it is absolutely impossible that it hasn't been propagated to GHP since then...
