### ISSUE TITLE
Hide Google Analytics ID from My Github Repo

### ISSUE THREAD

**Issue by 3N4N** [jekyll/minima#425]
This is not a bug report, just a query.

I don't understand how I can use Google-Analytics with minima theme. Everything else has been set up. The site is up and running and I have signed up for Google-Analytics and got a ID.

In the README, it is said, I should paste the ID in my "Jekyll site" but I don't understand what file that is. From a different website, I learnt that I should place that in my `_config.yml` file. But that would push my ID to public Github repository. Shouldn't I hide my private ID? I know I could make my repository private, but I rather wouldn't.

So, my question is:

> How do I set up Google-Analytics with Minima theme and not push the ID to my public Github repository?

**Comment by hszhakka** [comment]
The Google Analytics tracking ID is public, so you can put it in `_config.yml` without fear. If you worry some hackers corrupt your website data, you can set a [filter](https://support.google.com/analytics/answer/1034823?hl=en) in your Google Analytics account.

**Comment by 3N4N** [comment]
@hszhakka thanks for the response. I pushed the Google analytics ID. Would I need to fix something to prevent my `localhost:4000` traffic from being counted?

**Comment by hszhakka** [comment]
> @hszhakka thanks for the response. I pushed the Google analytics ID. Would I need to fix something to prevent my `localhost:4000` traffic from being counted?
> 
> **Edit**: Oh, and, I just need to put the ID in `_config.yml`, right? And ignore the `js` codes, right? Or do I have to put it in the pages manually in the `head` tag? How do I know if everything is set up correctly?

You don't need to do anything to prevent your `localhost` traffic if you don't run your website in a production environment.

You don't need to add any JS code in your website if you are using this theme because it has imported the JS code. The only thing you need to do is just configure your Google Analytics ID in `_config.yml`.
