### ISSUE TITLE
How to show the last modified date of a post?

### ISSUE THREAD

**Issue by hszhakka** [jekyll/minima#427]
In the current version, Minima only shows the published date (`page.date`) of a post. However, showing the last modified date after publishing to readers is useful. Is there a good strategy to show it beautifully and elegantly on a post?

**Comment by ashmaroli** [comment]
You may want to look at the plugin https://github.com/gjtorikian/jekyll-last-modified-at

However, it is not supported for direct use at GitHub Pages. You'll have to build the site locally or elsewhere.
Additionally, we won't be wiring Minima with any more plugins (even if they're supported on GHP) in the near future.

**Comment by hszhakka** [comment]
I have sent a PR #432
