### ISSUE TITLE
Default Minima example doesn't have any CSS on Github Pages

### ISSUE THREAD

**Issue by Tohaker** [jekyll/minima#431]
I've launched [a page](https://tohaker.github.io/GazeAwareRobotics/) using the Jekyll and the instructions [here](https://help.github.com/en/github/working-with-github-pages/creating-a-github-pages-site-with-jekyll) and it renders fine when I use bundle locally. When pushed to GitHub, however, it renders with literally no CSS:
![image](https://user-images.githubusercontent.com/33665681/72155786-cbcf3500-33ab-11ea-9a1b-3391d0a46fe5.png)

I've made no changes other than the text on the page, even the auto-generated example doesn't render.

What am I doing wrong?

**Comment by ashmaroli** [comment]
> What am I doing wrong?

When using GitHub to build *Project Pages*, you need to configure the `baseurl`:
```yaml
# _config.yml

baseurl: "/GazeAwareRobotics"
```
