### ISSUE TITLE
How to create a css rule for chapter breaks in short story

### ISSUE THREAD

**Issue by 3N4N** [jekyll/minima#453]
I have a simple layout for posting short fictions which I'm fairly happy with. For some stories with chapter breaks, though, I need to use a mark for chapter break. Personally, I use center-aligned `***` marks in word documents. I'd like to have the same in jekyll, if it's possible. I'd be open to any other system you guys could suggest. It doesn't really matter what I do as long as it works as a chapter break or a scene break.

So, just to clearly state, I specifically want a way to center-align whenever the text `***` (or `\*\*\*` since it's markdown) is written on a single line. Could I get some help?

By the way, here is my `_layouts/story.html` layout for short fictions.

```html
---
layout: default
---
<article class="story">

<header class="story-header">
<h1 class="story-title">{{ page.title | escape }}</h1>
</header>

<div class="story-first-para">
{{ page.excerpt }}
</div>
<div class="story-content">
<!-- {{ content }} -->
{{ content | remove_first:page.excerpt }}
</div>

</article>
```

**Comment by DirtyF** [comment]
HI, for general question avec Jekyll's usage, I'd suggest to post questions on https://talk.jekyllrb.com, thanks.

**Comment by 3N4N** [comment]
@DirtyF posted this question there. Being reviewed by moderator. Thanks.
