### ISSUE TITLE
Use minima-solarized/solarized-dark

### ISSUE THREAD

**Issue by gaetgu** [jekyll/minima#454]
I am working on creating a blog using the minima theme. I was just using the default theme when I decided to look for a darker one. I tried to use it first by modifying the _config.yml file and then by creating a custom scss file, but it sent me an email saying that "minima-solarized" could not be found. The contents of my assets/main.scss file are as follows:
```scss
---
# Bello!
---

$sol-is-dark: true;
@import "minima-solarized";
```
I am not sure why this is happening. I am using the minima theme by passing 
```yaml
theme: minima
```
through my config file. Any help?

-----
UPDATE
-----

Here is the contents of the email sent me:

The page build failed for the `master` branch with the following error:

Your SCSS file `assets/main.scss` has an error on line 2: File to import not found or unreadable: minima-solarized. Load path: /hoosegow/.bundle/ruby/2.5.0/gems/minima-2.5.1/_sass. For more information, see https://help.github.com/en/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#invalid-sass-or-scss.

**Comment by hszhakka** [comment]
It looks like you are using Minima 2.5, but customizable skins are the feature that would be introduced in Minima 3.0, which is not yet released. However, you can use directly the master branch of Minima by using `jekyll-remote-theme`. [Here](https://hszhakka.github.io/2020/01/20/launch-my-blog.html) are my steps, hope that is useful for you.

**Comment by gaetgu** [comment]
Thanks **so** much!!! I had tried something similar, by forking the minimal theme and trying to use it, but I had failed to add the "jekyll-remote-theme" plugin, so it didn't work. Now it does! Thanks again!
