### ISSUE TITLE
Remove the subscribe button on the home page

### ISSUE THREAD

**Issue by hszhakka** [jekyll/minima#457]
https://github.com/jekyll/minima/blob/d4bfaf248cf9632731b618dca4ce540975f23b20/_layouts/home.html#L59

Maybe this subscribe button can be removed since it's redundant because that the link to `feed.xml` revealed too on the social media list.

**Comment by DirtyF** [comment]
It could but text alternative on the RSS icon in the footer, should be something like "Susbcribe to this blog's feed' for example.

**Comment by hszhakka** [comment]
Alternatively delete the RSS icon from the footer, since it's not a kind of social media, literally.
