### ISSUE TITLE
Implementing Archive Pages

### ISSUE THREAD

**Issue by hszhakka** [jekyll/minima#463]
I know using `jekyll-archives` can automatically generate archive pages, but unfortunately, that plugin is still not supported by GitHub Pages!

- https://github.com/github/pages-gem/issues/93
- https://github.com/github/pages-gem/pull/106
- https://github.com/github/pages-gem/pull/643

The feature of archive pages almost being so basal to every blog, is it still outside the scope of Minima? If it is not, I am planning to implement some archive layouts in Minima, without `jekyll-archives`.

**Comment by DirtyF** [comment]
I don't feel like reinventing the wheel on this theme just for the sake of GitHub Pages, now that you can deploy through GitHub Actions, Netlify, Zeit now, Render, etc.
