### ISSUE TITLE
Cannot override custom-variables.scss and custom-styles.scss

### ISSUE THREAD

**Issue by hszhakka** [jekyll/minima#474]
## Summary

I am using jekyll-remote-theme to import the `master` branch of Minima, but I discover that I cannot override `custom-variables.scss` and `custom-styles.scss`. I put these two files into `_sass/minima/` in my repository, but after running `bundle exec jekyll serve`, the real imported files are still from the Minima repo.

Here is a CSS map:

<img width="816" alt="Screenshot 2020-02-20 at 6 47 04 PM" src="https://user-images.githubusercontent.com/59011975/74927014-d56ba400-5411-11ea-8883-6de99dc1f4b9.png">

Can anyone help me?

## Environment

- Jekyll: `4.0.0`
- Bundler: `2.1.4`
- jekyll-remote-theme: `0.4.1`
- Minima: the `master` branch

**Comment by ashmaroli** [comment]
The entry point is `@import "minima-{{ site.minima.skin | default: 'classic' }}";`. So when overriding Sass partials, you need to have at minimum, file ay path `minima-{{ site.minima.skin | default: 'classic' }}` for the overrides to be picked up.

**Comment by JJC1138** [comment]
I'm having this problem too (I've got my Gemfile accessing the current GitHub master version of minima).

Could you clarify that a bit @ashmaroli? Which folder exactly should the user's `custom-variables.scss` and `custom-styles.scss` files be placed in?

**Comment by hszhakka** [comment]
> The entry point is `@import "minima-{{ site.minima.skin | default: 'classic' }}";`. So when overriding Sass partials, you need to have at minimum, file of path matching
> `minima-{{ site.minima.skin | default: 'classic' }}` for the overrides to be picked up.

That sounds I need to copy multiple files into my repository, for example, if the skin is `classic`, I have to copy `_sass/minima-classic.scss`. Since it imports `mimima/initialize`, I have to copy `_sass/minima/initialize.scss`

**Comment by ashmaroli** [comment]
@JJC1138 As of this comment, to customize the CSS generated, place your `custom-variables.scss` or `custom-styles.scss` (whichever is relevant to the use-case) in the path `_sass/minima` at your source.

*In addition to this, you need to have the skin partial (i.e., if using the default skin then it would be
`minima-classic.scss`) at the root of `_sass` in your source to pull in your overrides.*

**Comment by hszhakka** [comment]
I have copied `custom-variables.scss`, `custom-styles.scss`, and `minima-classic.scss` into my repository, but only `custom-styles.scss` has been override:

<img width="606" alt="Screenshot 2020-02-21 at 1 51 40 PM" src="https://user-images.githubusercontent.com/59011975/75007986-b4f32680-54b1-11ea-9c86-878a9eb29378.png">

**Comment by ashmaroli** [comment]
I see.. Looks like to override `custom-variables.scss`, you need to copy `_sass/minima/initialize.scss` as well.. :frowning_face:

**Comment by ashmaroli** [comment]
This workflow needs to be improved..

**Comment by hszhakka** [comment]
> I see.. Looks like to override `custom-variables.scss`, you need to copy `_sass/minima/initialize.scss` as well.. ☹️

Even worse, after copying `_sass/minima/initialize.scss` into my repository, `jekyll serve` reported the below errors:

```shell
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/style-classic.scss':
                    Error: File to import not found or unreadable: base. on line 45:1 of _sass/minima/initialize.scss from line 87:1 of _sass/minima-classic.scss from line 1:1 of style-classic.scss >> @import ^ 
             Error: Error: File to import not found or unreadable: base. on line 45:1 of _sass/minima/initialize.scss from line 87:1 of _sass/minima-classic.scss from line 1:1 of style-classic.scss >> @import ^ 
             Error: Run jekyll build --trace for more information.
```

**Comment by JJC1138** [comment]
Thank you very much for looking into it. As a quick workaround, I made a `assets/css/style.scss` in my site which looks like this:

```
---
---
// my custom variables that Minima can use here

@import "minima-{{ site.minima.skin | default: 'classic' }}";

// my custom CSS rules that override Minima's rules here
```

That seems to work well, and has the nice property of only having to duplicate a trivial amount of Minima code in my project (the import line shown above).

I think the intended scheme of having the hooks to pull in the user's `custom-variables.scss` and `custom-styles.scss` would be nicer, but I'm afraid I'm a beginner at Jekyll and Sass, so I  don't understand why that doesn't work as it is.
