### ISSUE TITLE
Documentation may be misleading

### ISSUE THREAD

**Issue by Tonterias** [jekyll/minima#495]

**Comment by ashmaroli** [comment]
When referring a README on GitHub, always checkout the tag of the version you're using.
In your case, it would be `v2.5.1`: https://github.com/jekyll/minima/tree/v2.5.1#customize-navigation-links

The **`header_pages: [about.md]`** is documentation. You need to edit your config file and add those lines yourselves.

I don't see what is misleading here..

**Comment by Tonterias** [comment]
Sorry ashmaroli, It is my fault. I made it work. Thanks

**Comment by ashmaroli** [comment]
Its okay.
Happy Jekyllin'!
