### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by elijahmurray** [jekyll/minima#509]
Within the readme, it gives the wrong syntax for updating the pages shown in navigation.

```
header_pages:
  - about.md
  - portfolio.md
```

should be updated to

```
pages:
  - about.md
  - portfolio.md
```

**Comment by ashmaroli** [comment]
You are mistaken, my friend. The README is not wrong:
It gets used as follows:
https://github.com/jekyll/minima/blob/5283ae15420f4a8c1e4e3427389ffea2732771e6/_includes/header.html#L5
https://github.com/jekyll/minima/blob/5283ae15420f4a8c1e4e3427389ffea2732771e6/_includes/header.html#L21

**Comment by elijahmurray** [comment]
Guessing this changed in the past? Using `jekyll new my-site` installs minima 2.5.1 where `header_pages` doesn't work

**Comment by ashmaroli** [comment]
The following are from [`v2.5.1` tag](https://github.com/jekyll/minima/blob/v2.5.1/_includes/header.html):
(*You can verify at the link above*)
https://github.com/jekyll/minima/blob/38a84a949f9753c4542e25f422935f59b4913053/_includes/header.html#L5
https://github.com/jekyll/minima/blob/38a84a949f9753c4542e25f422935f59b4913053/_includes/header.html#L20

**Comment by elijahmurray** [comment]
Any idea why I'm seeing this then?

`/Users/myuseraccount/.rvm/gems/ruby-2.5.5/gems/minima-2.5.1/_includes/header.html`

![image](https://user-images.githubusercontent.com/3240306/79118423-e672ca80-7d5b-11ea-8b09-68ffb89919f7.png)

**Comment by ashmaroli** [comment]
You probably edited the gem sometime ago and forgot about it..?
The ln#3 doesn't exist at our end and so did the classname attribute `"wide-wrapper"`

To restore all gem versions back to their original state, you can run:
```
gem pristine minima
```
