### ISSUE TITLE
Feature Request: Built-in Minification

### ISSUE THREAD

**Issue by chaoscommencer** [jekyll/minima#513]
Have default.html layout use the compress layout provided by:
https://github.com/penibelst/jekyll-compress-html

This would provide minification by default.

**Comment by ashmaroli** [comment]
Thanks for the suggestion, but unfortunately we won't be supporting minification (especially via a Liquid layout for performance reasons &mdash; all those `{% if %}` and `{% for %}` are going to affect build times unnecessarily for a starter-theme.)
