### ISSUE TITLE
Modifying footer.html breaks social links

### ISSUE THREAD

**Issue by Tanjim131** [jekyll/minima#520]
I'm trying to add a custom copyright section to the footer.html section:

```
{%- if site.copyright -%}
    <li>&copy; {{ site.copyright }} {{ 'now' | date: "%Y"}} </li>
{%- endif %-}
```

I added the following filed in _config.yml file:

```
# New fields not defaulted by jekyll-new with the minima theme
# Add a copyright. A copyright symbol and year will be added automatically
# copyright: Company Name, Inc. 
copyright: "<My Name>"
```

But doing so removes my social icons. What am I doing wrong?

**Comment by ashmaroli** [comment]
Cannot tell for certain until we see the whole picture.
Please push your code into a public repository (or create a test-repo via `jekyll new`) and provide us the link to it.

**Comment by Tanjim131** [comment]
Link to the repo: https://github.com/Tanjim131/Personal-Blog

**Comment by ashmaroli** [comment]
I was waiting for you to realize the mistake by yourself. Well, I guess, you didn't see it yet.
You have a typo in your footer template:
```
{%- endif %-}
```
It should be:
```
{%- endif -%}
```

**Comment by Tanjim131** [comment]
Thanks! It was indeed a silly mistake.
