### ISSUE TITLE
duplicate lines

### ISSUE THREAD

**Issue by StartZeroGnu** [jekyll/minima#53]
Hi!

this is not a bug and does not affect operation

`custom_url` and `full_base_url` are defined in the "head" then, these lines are duplicated in "home" and "header"

```
{% assign custom_url = site.url | append: site.baseurl %}
{% assign full_base_url = custom_url | default: site.github.url %}
```

Bye!

**Comment by zdroid** [comment]
I think the issue has been fixed a few days ago. Please re-check it and close if it's really fixed. :wink:

**Comment by StartZeroGnu** [comment]
Fixed in this [commit](https://github.com/jekyll/minima/commit/c5f1213e940f6a73ca4dd9bec3280215abf30ad4). Thanks @zdroid for reminding me

**Comment by zdroid** [comment]
No problem. :smile:
