### ISSUE TITLE
Too-large header spacing on master branch

### ISSUE THREAD

**Issue by getaaron** [jekyll/minima#537]
Hi all,

I'm using minima on the [ScheduleBot Blog](https://blog.schedulebot.app) and recently switched:

|               | **Old**                  | **New**                       |
|---------------|--------------------------|-------------------------------|
| `Gemfile`     | `gem "minima", "~> 2.5"` | `gem "jekyll-remote-theme"`   |
| `_config.yml` | `theme: minima`          | `remote_theme: jekyll/minima` |

so that I could use the new `custom-head.html` feature.

There's now lots of extra spacing above headers. For example, here are some screenshots (from [this post](https://blog.schedulebot.app/schedulebot/scheduling/2020/09/01/employee-work-scheduling-constraints-shouldn-t-be-this-hard.html) if you need a live example):

## Old Appearance

<img width="1404" alt="image" src="https://user-images.githubusercontent.com/789577/91980934-aa7dd900-eced-11ea-8950-5c29e4b1db6a.png">

## New Appearance

<img width="1404" alt="image" src="https://user-images.githubusercontent.com/789577/91980876-920dbe80-eced-11ea-9753-090a409ffba7.png">

## Question

- Is this change intentional, or a bug?
- If it's intentional, what's the preferred approach to override it?

**Comment by ashmaroli** [comment]
This change was intentionally made in https://github.com/jekyll/minima/commit/88ef462a3725500e6e5bdb27abb258c8c8b1670f.
However, I now feel like agreeing with you that the top margin is a bit too much.

**Comment by getaaron** [comment]
@ashmaroli I opened a PR, let me know what you think.

**Comment by ngzhio** [comment]
This is only about personal aesthetics. How to make everyone satisfied?

**Comment by ashmaroli** [comment]
> How to make everyone satisfied?

@ngzhio That's very difficult and almost impossible. But in this case, I think we can meet halfway to satisfy the aesthetic qualms of all three parties..
