### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by dougbreaux** [jekyll/minima#544]
Please update the README to explain how to use Pagination with the current version of Minima.

There is clearly some level of support in home.html, but that doesn't seem to correlate to the Jekyll docs that seem to assume index.html in some particular path.

I've tried on [my GitHub Pages blog](https://github.com/dougbreaux/dougbreaux.github.io), where I've enabled `remote_theme: minima`, and can tell that's working, but all my attempts at enabling pagination have failed, resulting in a blank home page.

**Comment by ashmaroli** [comment]
Technically, Minima doesn't expect any special markup or configuration to obtain pagination with `jekyll-paginate` gem.
But yes, `jekyll-paginate` does ask for some:
- have `index.html` instead of `index.md`.
- set how many items per page by setting `paginate` key in config file.

**Comment by dougbreaux** [comment]
You can see commented out in my [_config.yml](https://github.com/dougbreaux/dougbreaux.github.io/blob/master/_config.yml) that I've tried variations of that, including replacing my `index.md` with `index.htm`l, and putting an `index.html` in a path and attempting to use that path in the paginate settings. So there's clearly more to it. A working example would be fantastic.

**Comment by ashmaroli** [comment]
I agree with having a working example. But for now, you can just **clone this repository locally**, add `jekyll-paginate` to the Gemfile and config file; configure pagination by adding `paginate: 2` and renaming the `index.md` to `index.html`.
Now, run `bundle exec jekyll serve` and preview in your browser.

**Comment by dougbreaux** [comment]
I don't have a Gemfile at all, and am only on GitHub Pages, so I don't have anything installed to run locally. But I'm guessing just the commit/push will trigger the one run fine.

I did try renaming `index.md`, and I ended up with only `index.html` being shown, none of the Minima scaffolding around it.

**Comment by ashmaroli** [comment]
I was referring to the Gemfile of this repository (`jekyll/minima`).

> I did try renaming `index.md`, and I ended up with only `index.html` being shown

Did you try adding `layout: home` to the front matter?

**Comment by dougbreaux** [comment]
Ok, that did the trick, thanks. I still say this should be documented in the README, though.
