### ISSUE TITLE
Custom Sass overrides do not appear to be working

### ISSUE THREAD

**Issue by clhenrick** [jekyll/minima#545]
I've tried [following your instructions](https://github.com/jekyll/minima#customizing-templates) for overriding Sass variables and cannot seem to get it to work. The instructions for doing so are a bit confusing, it's not clear if the `initialize.scss` is needed or not in order to only override a Sass variable that's already defined in the theme.

Here's what I've tried:

- created a new Jekyll project with the minima theme (v2.5.1)
- created a `_sass/minima/custom-variables.scss` file with `$base-font-family: serif;` This had no effect.
- created a `assets/css/styles.scss` file with:

```scss
@import "minima/skins/{{ site.minima.skin | default: 'classic' }}";
@import "minima/initialize";

$base-font-family: serif;
```

That throws errors if I don't have the skin and initialize files in the `_sass/minima/` and `_sass/minima/skins` directories, so I added those directories and files too.

However after doing that I got errors for other missing `.scss` files so I then copied over everything from the master branch's `_sass` and `assets/css` directories to my project. This still had no effect with the custom Sass variable override.

I then tried editing the value of the variable `$base-font-family` in `_sass/minima/initialize.scss`, but this also had no effect. With all of these steps I've also tried removing the `.jekyll-cache` directory, restarting the local server, and clearing my browser cache.

**Comment by clhenrick** [comment]
FYI, the code may be viewed here: https://github.com/SatcherInstitute/website/tree/test-netlify-pr-preview
and deploy preview here: https://deploy-preview-2--affectionate-kepler-36cf3b.netlify.app/

**Comment by ashmaroli** [comment]
The instructions you're referring to is for the unreleased `master` branch. For that you need to be using the repository-version of the theme not the released gem version.
For the gem version, v2.5.1, the instructions are at https://github.com/jekyll/minima/tree/v2.5.1#customization

**Comment by clhenrick** [comment]
Thanks for clarifying, I will try that.

-Chris
