### ISSUE TITLE
Improve loading time

### ISSUE THREAD

**Issue by oncleben31** [jekyll/minima#55]
There are some optimization identified by [Google insights](https://developers.google.com/speed/pagespeed/insights/)

Is it possible to improve the score ?

Currently:
-   Mobile
  - loading time 90/100
  - user experience 90/100
-   PC 96/100

**Comment by zdroid** [comment]
I'm guessing you're talking about your site, http://oncleben31.cc. [Here](https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Foncleben31.cc) is its insights result.

Basically, the speed "issues" aren't that important at all and the specified solutions don't change much for small websites. You can google how to implement those methods of speeding up the page load, but they have nothing to do with Minima. It's more of one's preferences

I do agree on mobile user experience rating though, as the social icons really are small. I'll submit a PR to fix that.

**Comment by oncleben31** [comment]
Thanks for the clarification. If the optimization is not standard for everybody or not related directly to minima, let forget this part.
The second part is about user experience should be improved on a mobile small screen. I share your point of view. So let's focus on this part too. 

> I can submit a PR for that.

Please do as my skills in CSS are very low.

**Comment by zdroid** [comment]
I've got it to something like this by adding 5px padding between the elements:

![the way to go](https://cloud.githubusercontent.com/assets/2725611/19223564/236bfdb6-8e73-11e6-8ad2-7c4126a59630.jpg)


I've also removed the link from icons as they are gray and users don't expect from something gray to be a link. If it looks good, I'll send a PR. :shipit:

**Comment by pathawks** [comment]
Clicking on the icon should be the same as clicking on the label. It doesn't need to be underlined, but it _does_ need to be a link.

**Comment by oncleben31** [comment]
Do you want me to test it on my site to see if the warning of Google insight goes away ? Or have you test is on your side ?

**Comment by zdroid** [comment]
ok @pathawks, I'll fix it and test it tomorrow

**Comment by ducblog** [comment]
If your CSS content is not much, you can inline CSS style:

- Open CSS file -> copy CSS content
- Open _include/head.html  -> delete line :

<link rel="stylesheet" href="http://oncleben31.cc/css/main.css">

and insert:

<style type="text/css">
...Paste CSS which copied here...
</style>

That's this. Get your high score!

**Comment by pathawks** [comment]
> you can inline CSS style

This is a bad idea. With HTTP/2 there is no roundtrip penalty anymore, and you are only guaranteeing that the asset will be served from a cache. [This is bad. Don't do it.](https://blog.cloudflare.com/http-2-for-web-developers/#bestpracticesforhttp2weboptimization)

Test suites are helpful, but at the end of the day we design our sites for users, not tests :+1:

**Comment by caspervonb** [comment]
> ...Paste CSS which were copied here...

Don't do that, use a partial or scssify an import `{{ "@import "base" | scssify }}` 
Wrote about it a while ago https://hasharray.pw/tutorials/jekyll/inlining-critical-above-the-fold-stylesheets-in-a-jekyll-website

> This is a bad idea. With HTTP/2 there is no roundtrip penalty anymore, and you are only guaranteeing that the asset will be served from a cache. This is bad. Don't do it.

Even with http/2, inlining will still be the fastest way to get things rendering, won't it?

**Comment by pathawks** [comment]
> Even with http/2, inlining will still be the fastest way to get things rendering, won't it?

Nope. See the [article I linked to explaining why inlining delays time to first paint.](https://blog.cloudflare.com/http-2-for-web-developers/#bestpracticesforhttp2weboptimization)
