### ISSUE TITLE
open link to external websites in a NEW TAB

### ISSUE THREAD

**Issue by yshmarov** [jekyll/minima#554]
IMHO the only thing the theme misses is opening links_to external websites in a new tab.

When blogging you often add links to external websites, however you don't want the user to leaver your blog.

**Comment by ashmaroli** [comment]
When a user adds links to external websites, the responsibility falls on the user to add the necessary attributes to make those links open in a new tab/window.

If you're new to using *Jekyll et al* / kramdown etc. try using inline attributes. For example:
```
[Google](https://www.google.com) {:target="blank"}
```
