### ISSUE TITLE
Add `relative_url` filter to minima 

### ISSUE THREAD

**Issue by ashmaroli** [jekyll/minima#56]
I think we should update relevant files to use the new `relative_url` as a live example of its usage. I'm not opening a PR as I'm not sure regarding the `site.github.url` bit.

--
/cc @jekyll/minima

**Comment by benbalter** [comment]
> I'm not sure regarding the site.github.url bit.

GitHub Pages now sets `site.url` and `site.baseurl` in anticipation of Jekyll 3.3, meaning `absolute_url` and `relative_url` should always work as expected, even with no value explicitly set.

**Comment by ashmaroli** [comment]
Thats great! If either of you haven't started work on a pull, regarding this, i will start..

**Comment by benbalter** [comment]
> If either of you haven't started work on a pull, regarding this, i will start..

Please do!

**Comment by benbalter** [comment]
> GitHub Pages now sets site.url and site.baseurl

The relevant PR, if you're interested: https://github.com/jekyll/github-metadata/pull/76

**Comment by ashmaroli** [comment]
Thanks :smiley:
