### ISSUE TITLE
Disable RSS feed generation

### ISSUE THREAD

**Issue by dataframing** [jekyll/minima#562]
Hi all,

I'm using Jekyll and `minima` through [fastpages](https://github.com/fastai/fastpages). I've noticed that for a very short post history (1 or 2 posts so far, running locally) it takes ~14-15 seconds for `Jekyll Feed: Generating feed for posts` to finish. This makes local development and experimentation take much longer than I'd hope.

[I've raised an issue on the `fastpages` repo](https://github.com/fastai/fastpages/issues/453), but it seems more fitting to ask here: **is there a good way to completely disable the `jekyll-feed` plugin/generation?** It does seem like this was [raised before](https://github.com/jekyll/minima/issues/522) back in May, but went stale due to lack of responses.

I'd appreciate any insight here, even if it's "No, we can't do that yet." Also happy to help contribute towards a solution, if it's within reach! Thank you 👍

**Comment by ashmaroli** [comment]
There is no official way to disable a plugin that has already been loaded.
But since you're using a service to render and then deploy via GitHub Pages, there is a workaround by using a local plugin.
Create a Ruby file at path `<source>/_plugins/feed_generator_override.rb` with the following content:
```ruby
# frozen_string_literal: true

module JekyllFeed
  class Generator < Jekyll::Generator
    safe true
    priority :lowest

    # Main plugin action, called by Jekyll-core
    def generate(_site)
    end
  end
end
```
