### ISSUE TITLE
Confign information not shown on page

### ISSUE THREAD

**Issue by matej2** [jekyll/minima#565]
Hello,

I am new to Jekyll and I am having some problems with the configuration. I am trying to add site author and social links. However, they are not showing on the page. Also I am not getting any errors. 

I created a fresh copy of `jekyll new theme` page. I added additional details in configuration file, however the added information is not showing on the page. 

It is not showing the following informations:

- `site.author.name` anr `site.author.email`
- anything under `minima.social_links`

Source code is here: [https://github.com/Skupina6/skupina6.github.io/tree/new-theme](https://github.com/Skupina6/skupina6.github.io/tree/new-theme). I ran it with `jekyll serve`

Is there something that I missed? Do I need to add icons / assets?

Thanks for your help

**Comment by techapplied** [comment]
I think you need to run bundle update to make configuration file changes show.

**Comment by matej2** [comment]
I updated bundle, however I still have the issue

**Comment by ashmaroli** [comment]
@matej2 Your Gemfile is using the released version of `minima` theme.
The feature you're looking for has not been released.

Since you're using GitHub Pages to deploy your site, use the `jekyll-remote-theme` plugin and point to this repository by editing your config file:

```diff
# _config.yml

- theme: minima
+ remote_theme: jekyll/minima
  plugins:
    - jekyll-feed
+   - jekyll-remote-theme
```

**Comment by matej2** [comment]
Thanks a lot, it worked.
