### ISSUE TITLE
How to add reading time to my blog posts?

### ISSUE THREAD

**Issue by TakreemAkhter** [jekyll/minima#566]
I read [this article](https://jekyllcodex.org/without-plugin/reading-time-indicator/#) where the author asks us to add the .html file to _includes and place `{% include reading-time.html %}` to your layout on the place where you want the reading time indicator to appear. I use the layout of this theme. How can I add reading-time indicator to my posts?

**Comment by sziv2p** [comment]
Do what that article says in your own repository.

**Comment by TakreemAkhter** [comment]
How can I implement this in you own repository for my blog? I do not have a _layouts folder in my repo, instead I use this theme's layout. [Please do have a look my repo](https://github.com/TakreemAkhter/TakreemAkhter.github.io).
Thanks for the help!

**Comment by sziv2p** [comment]
> How can I implement this in you own repository for my blog? I do not have a _layouts folder in my repo, instead I use this theme's layout. [Please do have a look my repo](https://github.com/TakreemAkhter/TakreemAkhter.github.io).
> Thanks for the help!

You can copy the `_layouts` folder into your repo, then modify it.

**Comment by TakreemAkhter** [comment]
> You can copy the _layouts folder into your repo, then modify it.
thanks for your help
