### ISSUE TITLE
How to remove the white bar in the header?

### ISSUE THREAD

**Issue by Merrit** [jekyll/minima#581]
Theme is excellent, I just need to remove the odd white spacer at the top of the header. How can I accomplish this?

![image](https://user-images.githubusercontent.com/9575627/110966249-112a2200-8323-11eb-98b7-f9e34ea1b64a.png)

![image](https://user-images.githubusercontent.com/9575627/110966456-420a5700-8323-11eb-89b4-02a62cc80f75.png)

**Comment by zivhub** [comment]
Delete this line https://github.com/jekyll/minima/blob/3cdd14dff1216f561c68329e0b7420c2dc9b796a/_sass/minima/_layout.scss#L5

**Comment by Merrit** [comment]
Perfect, exactly what I needed. Thank you! :heart:
