### ISSUE TITLE
[Question] How do I not show links in excerpts?

### ISSUE THREAD

**Issue by p2635** [jekyll/minima#588]
How do I not show links in excerpts?
![圖片](https://user-images.githubusercontent.com/4522927/118402224-ea5cd480-b660-11eb-840d-69e220d8eb90.png)

If this isn't the right place to ask for support, sorry about that. Please direct me to the right channel for that.

**Comment by travisdowns** [comment]
You don't have to use the first paragraph as an excerpt, you can write an explicit excerpt using `excerpt:` in the front-matter, so you can copy/paste your desired text and remove the links in the excerpt.

**Comment by p2635** [comment]
thanks @travisdowns , that's good but I'd rather not specify an explicit excerpt for each post that I published. Is there a way I can set minima so links are shown as plain text (not hyperlinks) in the excerpt?

**Comment by travisdowns** [comment]
@p2635 - well there doesn't seem to be any built-in way, but you could override the home.html layout and change the {{ post.excerpt }} to soemthing like {{ post.excerpt | markdownify | strip_html }}.

**Comment by p2635** [comment]
thanks I'll try that and close this down @travisdowns
