### ISSUE TITLE
Unable to override custom-variables

### ISSUE THREAD

**Issue by mcpwns** [jekyll/minima#602]
Hi, I'm new to jekyll and the themes. I'm using v`2.5.1` of minima and I created `custom-variables.scss` in my site's `_sass/minima/` directory and none of the overrides are getting picked up. Am I missing something?

**Comment by gusano** [comment]
@mcpwns I believe those instructions are for the latest git version of minima and were not implemented yet in `v2.5.1`.
Check the [doc for `v2.5.1`](https://github.com/jekyll/minima/tree/38a84a949f9753c4542e25f422935f59b4913053).
