### ISSUE TITLE
inconsistency in _config.yml use depending on gem mode

### ISSUE THREAD

**Issue by travisdowns** [jekyll/minima#603]
The root of the theme contains a `_config.yml` and Jekyll 4 will use the theme's configuration values if they aren't already set in the site's _config.yml.

However, the _config.yml isn't specified in the `files` property of the gemspec, so when packaged as a gem and used that way (e.g., via rubygems), the _config.yml values aren't applied.

However, when cloned locally and used that way, the _config file is present and read, resulting in a different build, because of different site properties.

Which is the correct behavior isn't clear: is `_config.yml` intended as defaults for unspecified values, or just as a template/documentation of the available properties? Based on the inspection of the file, I think the latter. In that case, maybe it can be renamed to `_config-example.yml` or similar.

**Comment by ashmaroli** [comment]
@travisdowns Thank you for reaching out to us.
I agree there is inconsistency in the resulting build. I feel this needs to be addressed in Jekyll Core as well.

However, the best solution w.r.t Minima (for the time being) is to change the extension of the config file to `.yaml`.

**Comment by travisdowns** [comment]
> However, the best solution w.r.t Minima (for the time being) is to change the extension of the config file to `.yaml`.

In my case, I work around it by setting

~~~

~~~
ignore_theme_config: true
~~~

in my site's `_config.yml` to always ignore the theme's config since then I don't have to modify minima.

> I feel this needs to be addressed in Jekyll Core as well.

Agreed, I wasn't sure where to file the that issue.

**Comment by ashmaroli** [comment]
> ignore_theme_config: true

Oh right. I forgot about that provision. So, the issue has already been handled.

**Comment by travisdowns** [comment]
> So, the issue has already been handled.

This is a viable workaround but I still think this file should not be present in the gem if it is not intended to be injected into the using site's config, since that's what happens by default. Few users will ever set `ignore_theme_config`.

**Comment by ashmaroli** [comment]
> this file should not be present in the gem if it is not intended to be injected into...

*Technically, the file is not present in the gem* (because it isn't included in the theme's gemspec like you mentioned).
And Jekyll 4 loads the config file only if one is using the theme-repository **directly**. Like I said previously, therefore this is not an issue with Minima (or any theme-repository). Its a Jekyll 4 issue.

Since there is a builtin workaround in Jekyll 4, the scope for complaint is very narrow.
As I see it, the solution you desire is to make `ignore_theme_config` setting redundant with a patch. But that is for the folks behind Jekyll 4 upstream to decide, not downstream theme projects.

**Comment by travisdowns** [comment]
> As I see it, the solution you desire is to make `ignore_theme_config` setting redundant with a patch. But that is for the folks behind Jekyll 4 upstream to decide, not downstream theme projects.

Yes, I agree. Feel free to close this issue.

**Comment by travisdowns** [comment]
> And Jekyll 4 loads the config file only if one is using the theme-repository **directly**

I believe it also happens if you specify the gem e.g., via `github` link in the Gemfile, but I didn't check.

**Comment by travisdowns** [comment]
Closing this since it's not really a problem in minima as you point out.
