### ISSUE TITLE
Single table

### ISSUE THREAD

**Issue by jjacenty** [jekyll/minima#612]
You can create a single table in GitHub, but not in a minima.
How To Make A Single Table?

| Test | Single table test |
|--------|------------------------------------------|

**Comment by jjacenty** [comment]
I mean the headline itself, 

```
| Test | Single table test |
|--------|------------------------------------------|
```

**Comment by jjacenty** [comment]
But GitHub allows you to make one table according to this schema:

```
| Test | Single table test |
|--------|------------------------------------------|
```
result

| Test | Single table test |
|--------|------------------------------------------|

**Comment by jjacenty** [comment]
> To render a single-row table, do not include the separator:
> 
> ```
> | Test | Single table test |
> ```
> 
> or
> 
> ```
> Test | Single table test
> ```


How to set your way to left, center, right?

**Comment by ashmaroli** [comment]
@jjacenty Please report this issue at https://github.com/gettalong/kramdown if your site is using `kramdown` as the Markdown parser.
