### ISSUE TITLE
_includes/head.html extra '/'

### ISSUE THREAD

**Issue by phpeterson-usf** [jekyll/minima#622]
I'm building a [site template](https://github.com/phpeterson-usf/cyte) for my university classes. I find that when I deploy the site to Github pages, `style.css` is 404 and the URL is wrong, ignoring my `baseurl`. Perhaps [minima's head.html](https://github.com/jekyll/minima/blob/master/_includes/head.html#L6) has a leading '/' it shouldn't have? Works ok if I copy minima's `head.html` into my `_includes/` and remove the leading '/' on the URL to `style.css`

**Comment by ashmaroli** [comment]
Is this ticket still relevant, @phpeterson-usf?
Everything seems to work as expected..

**Comment by phpeterson-usf** [comment]
Hi @ashmaroli, are you saying that it's expected that I need to copy minima's `_includes/head.html` into my `_includes/` and remove the leading '/' from the `style.css` URL? I'm new to jekyll but that seemed like an odd solution to getting 404 on style.css due to missing `baseurl`. I could back out my "fix" if that helps show you what I mean.

**Comment by ashmaroli** [comment]
> are you saying that it's expected that I need to copy minima's `_includes/head.html` into my `_includes/` and remove the leading '/' from the `style.css` URL?

No. I'm saying that the leading slash needn't be removed at all.
And your site should work as expected irrespective of the leading slash.

> I could back out my "fix" if that helps show you what I mean.

That would be great.

**Comment by phpeterson-usf** [comment]
Tried unsuccessfully to repro. Sorry to distract, but appreciate the work on Jekyll and Minima.
