### ISSUE TITLE
Disqus doesn't work

### ISSUE THREAD

**Issue by EmilySeville7cfg** [jekyll/minima#626]
Disqus [doesn't work](https://console-utils.github.io/congratulations/2021/12/29/2022-year-congratulations.html) (link to my GitHub pages-based site with page where Disqus comments are expected) in minima even with `shortname` set:

```yml
disqus:
  shortname: consoleutils
```

and Disqus configured:

![image](https://user-images.githubusercontent.com/42812113/147749444-7c641fb9-0606-465c-8587-b1d6fb299e7a.png)

Site source code is [here](https://github.com/Console-Utils/console-utils.github.io).

**Comment by EmilySeville7cfg** [comment]
If I am wrong or it's a Disqus issue please notify me. ;)

**Comment by mzhang001** [comment]
You might also need to put the url into the _config.yml

**Comment by EmilySeville7cfg** [comment]
Thanks! Specifying `url` field helped. ;) What about to note it in README?

**Comment by mzhang001** [comment]
Good idea, pull request made https://github.com/mzhang001/minima/pull/1
