### ISSUE TITLE
not meant to be forked?

### ISSUE THREAD

**Issue by rahil627** [jekyll/minima#635]
hullo.

this is quite a newbie problem, pardon me... but:

i understand i can “override” many of the files to customize the theme to my liking, but is it not meant to be completely forked? I’m running into some errors with just a clean fork (something to do with the feed_meta in head.html)... is there some hidden magics happening between the original repo and jekyll?..

if so, maybe can add a giant disclaimer, DO NOT FORK? haha.

**Comment by ashmaroli** [comment]
Hi,
There is no limitation to forking this repository.
What exactly is the error that you're encountering?

**Comment by rahil627** [comment]
ohhhhh snap! I thought the original config file was like the default values, and then my own config would go on top of that. Okay, I now understand, thanks!
