### ISSUE TITLE
Inline SVG v SVG files

### ISSUE THREAD

**Issue by Eitot** [jekyll/minima#64]
Is it not better to use SVG files instead of inline SVG in the light of HTTP/2?

**Comment by DirtyF** [comment]
IMHO: HTTP/2 is not everywhere yet, but for caching, I'd rather use files to be able to specify the ones who changed in a service worker for instance.

**Comment by Eitot** [comment]
I had the caching in mind as well. The Twitter and Github templates can be used multiple times and I think it would be more efficient to store them in files instead.

**Comment by tioover** [comment]
And SVG sprite https://css-tricks.com/svg-sprites-use-better-icon-fonts/

**Comment by tioover** [comment]
I written a commit, to demonstrate how to use.

**Comment by jpdevries** [comment]
> IMHO: HTTP/2 is not everywhere yet, but for caching, I'd rather use files to be able to specify the ones who changed in a service worker for instance.

Agreed. SVG `<use>` has landed in Edge now so SVG sprites are fairly safe to use now.

**Comment by ashawley** [comment]
Was done in #141.  Close?
