### ISSUE TITLE
Loading minima as remote theme.

### ISSUE THREAD

**Issue by pozilei** [jekyll/minima#642]
In fact, you don't have to wait for the release of 3.0. You can directly use the master branch of Minima by using `jekyll-remote-theme`. [Here](https://hszhakka.github.io/2020/01/20/launch-my-blog.html) are my steps, hope that is useful for you.

_Originally posted by @hszhakka in https://github.com/jekyll/minima/issues/420#issuecomment-581741876_

website down, can you reup?

**Comment by ramottamado** [comment]
Use this: https://github.com/benbalter/jekyll-remote-theme

Change the remote theme name to `jekyll/minima`

**Comment by pozilei** [comment]
After following the instructions in the link, when serving jekyll I get this error: ```ERROR `/assets/main.css' not found.```.

this is my dir structure:

├── 404.html
├── CNAME
├── Gemfile
├── Gemfile.lock
├── _config.yml
├── _includes
│   ├── footer.html
│   └── head.html
├── _layouts
│   ├── default.html
│   ├── home.html
│   └── page.html
├── _posts
│   ├── 2022-01-19-hello-world.markdown
│   └── 2022-01-26-SELO-<3.markdown
├── _sass
├── _site
│   ├── 404.html
│   ├── CNAME
│   ├── about
│   │   ├── contact
│   │   │   └── index.html
│   │   └── impressum
│   │       └── index.html
│   ├── android-chrome-192x192.png
│   ├── android-chrome-512x512.png
│   ├── apple-touch-icon.png
│   ├── assets
│   │   ├── css
│   │   │   ├── formspree.css
│   │   │   ├── style.css
│   │   │   └── style.css.map
│   │   └── minima-social-icons.svg
│   ├── best-granddad
│   │   └── index.html
│   ├── favicon-16x16.png
│   ├── favicon-32x32.png
│   ├── favicon.ico
│   ├── feed.xml
│   ├── hello-world
│   │   └── index.html
│   ├── index.html
│   ├── robots.txt
│   ├── site.webmanifest
│   └── sitemap.xml
├── about.markdown
├── android-chrome-192x192.png
├── android-chrome-512x512.png
├── apple-touch-icon.png
├── assets
│   ├── css
│   │   └── formspree.css
│   ├── images
│   └── js
├── cv-contact.html
├── data
├── favicon-16x16.png
├── favicon-32x32.png
├── favicon.ico
├── index.markdown
├── robots.txt
└── site.webmanifest

**Comment by ramottamado** [comment]
I think some your includes still reference old paths for Minima's style sheet.

Try removing the folders `_layouts` and `_includes`. Or, if you made some customisation, you need to compare and adapt with corresponding files in Minima master branch.
