### ISSUE TITLE
[MAJOR BUG] Minima is incompatible with github-pages

### ISSUE THREAD

**Issue by ItsIgnacioPortal** [jekyll/minima#646]
Following the instructions on the gemfile, commenting the gem "jekyll", and uncommenting the gem "github-pages" causes a conflict when running `bundle install`. Running `bundle update` does not fix it:

```
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies.....
Bundler could not find compatible versions for gem "jekyll-feed":
  In snapshot (Gemfile.lock):
    jekyll-feed (>= 0.16.0)

  In Gemfile:
    github-pages was resolved to 36, which depends on
      jekyll-feed (= 0.2.3)

    minima (~> 2.5) was resolved to 2.5.1, which depends on
      jekyll-feed (~> 0.9)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.a
```

Minima need an update so it's compatible with the latest `github-pages` (225). As it is now, **it's impossible to deploy jekyll on github-pages with the default theme.** Also, was this ever compatible with github-pages?

**Comment by roblesch** [comment]
I have been hosting my blog on github pages without issue with the following Gemfile for the past few months -

```
source "https://rubygems.org"
gem "github-pages", "~> 219", group: :jekyll_plugins
gem "minima", "~> 2.5"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.15"
end

gem "webrick", "~> 1.7"
```

**Comment by ItsIgnacioPortal** [comment]
Nevermind, I've moved my project to [Ghost](github.com/tryghost/ghost).
