### ISSUE TITLE
emoji characters lose their color in edge/chrome on windows system

### ISSUE THREAD

**Issue by jeffatoptics** [jekyll/minima#653]
## Problem Description:

I have a page with emoji characters, such as 🐬

- they lose their color in edge/chrome browsers in windows system as below. they just follow the font color style defined for the page fonts.

[emoji lose color](https://github.com/jeffatoptics/jeffblog/blob/main/assets/20220503/bw-emoji.png)

- but they still look good in firefox in any system, and also ok in browsers of android system. 

[emoji with color](https://github.com/jeffatoptics/jeffblog/blob/main/assets/20220503/color-emoji.png)

## Solution:  

this is easy and minor change. In style.css definition, the font family shall present "Segoe UI Emoji" before "Segoe UI Symbol". I changed the sequence in `initialize.scss` , and this fix the above problem.

more detais:

[initialize.scss](https://github.com/jekyll/minima/blob/master/_sass/minima/initialize.scss) has the following definition
```
$base-font-family: -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", "Segoe UI Symbol", "Segoe UI Emoji", "Apple Color Emoji", Roboto, Helvetica, Arial, sans-serif !default;
```
change it to

```
$base-font-family: -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", "Segoe UI Emoji", "Segoe UI Symbol", "Apple Color Emoji", Roboto, Helvetica, Arial, sans-serif !default;
```

**Comment by ashmaroli** [comment]
@jeffatoptics You are free to submit a pull request to fix the issue for all users of this theme.
Thanks.

**Comment by jeffatoptics** [comment]
@ashmaroli  thank you. i just submit a PR.
