### ISSUE TITLE
Missing dependency webrick?

### ISSUE THREAD

**Issue by Uzlopak** [jekyll/minima#655]
I tried to test this theme locally, but it threw an error. It could not require webrick. I manually added the gem to the Gemfile, installed again and then it worked.

Is there a reason why this gem is missing?

**Comment by ashmaroli** [comment]
@Uzlopak The reason is because newer versions of ***Ruby*** (`>= 3.0.0`) stopped bundling `webrick` by default.
Jekyll 4.3.0 onward will have the gem marked as a dependency to counter this situation.
