### ISSUE TITLE
How to use Minima theme so that socials appear in footer of page AND google analytics receives data?

### ISSUE THREAD

**Issue by jrossner** [jekyll/minima#659]
I have created a Jekyll blog with the minima theme and have noticed two issues:

1) If I use the "default" minima theme, my google analytics (GA4) property doesn't receive data, but everything is rendering as expected on the page.

2) If I use the remote-theme version of minima, my google analytics property does receive data, but the socials specified in my config file are not rendered in the footer. I inspected the html being rendered and there is a "social-links" element and an empty "social-media-list" unordered list.

I have been experimenting with configurations in my [Gemfile](https://github.com/jrossner/criticalcelticsfan/blob/main/Gemfile) and [Config file](https://github.com/jrossner/criticalcelticsfan/blob/main/_config.yml) without success.

Is anyone else experiencing  similar issues? I appreciate any pointers on what I'm missing.

**Comment by ashmaroli** [comment]
Hi, if you're using the theme via remote_theme, then social media should be configured as `minima.social_links`. For example:
```
minima:
  social_links:
    twitter: jekyllrb
```
Refer the README doc on the `master` branch for further details.

**Comment by jrossner** [comment]
> Hi, if you're using the theme via remote_theme, then social media should be configured as `minima.social_links`. For example:
> 
> ```
> minima:
>   social_links:
>     twitter: jekyllrb
> ```
> 
> Refer the README doc on the `master` branch for further details.

Perfect, thank you! I had not included the minima line previously
