### ISSUE TITLE
Feature Request: Support for PixelFed in Social Settings

### ISSUE THREAD

**Issue by flowinho** [jekyll/minima#679]
Hello there!

I would love to have support for linking my PixelFed-Profile in the Footer using Minima.

PixelFed is a decentralized alternative to Instagram. It's like Mastodon is for Twitter.

Example: https://pixelfed.social/flowinho

Would this be possible? ☺️

Best wishes from southern Germany.

**Comment by ashmaroli** [comment]
We're no longer accepting further additions to our social-icon list.
Moreover, the template has been modified to enable users to add their desired social link at their end.
Please refer the README document for details.
