### ISSUE TITLE
Hyperlink in "description" _config.yml?

### ISSUE THREAD

**Issue by orschiro** [jekyll/minima#68]
Dear all, 

Is it possible to support hyperlinks in the "description" of the _config.yml file?

**Comment by ashmaroli** [comment]
I cant see how that'd be a good addition.. can you please elaborate with an example?

**Comment by orschiro** [comment]
For example, to put the link to another website into the short description
that is shown in the bottom right. This might represent a link to the
person who created the website.

**Comment by ashmaroli** [comment]
The 'description' info is also used as a [metadata](https://github.com/jekyll/minima/blob/master/_includes/head.html#L7) for the site using <meta name="description"[..]> and as I see it, there's no way to have a link be defined within the description.

Alternatively, *minima* does support `site.author` if it exists. You could expand on that and have it link to the webmaster's portfolio.

**Comment by orschiro** [comment]
Nice alternative, thanks!

**Comment by steremma** [comment]
I am reviving this thread because I am interested in a similar functionality: I would like to add hyperlinks into the text description of my projects. For example:

```
- name: Project Title
  i18n: name
  repo: https://github.com/steremma/root
  url: https://gist.github.com/steremma/048549de16cc48610233c943ecf495b4
  img: /static/assets/img/landing/google.png
  desc: My framework outperforms the [current industry standard](link to its homepage)
 as can be seen in publicly available [benchmarks](link to blog post or whatever).

```

**Comment by mhalomari** [comment]
> desc: My framework outperforms the [current industry standard](link to its homepage)
>  as can be seen in publicly available [benchmarks](link to blog post or whatever).

Hi... I tried several options and it worked like this:
`desc: My framework outperforms the ,a href="link to its homepage">current industry standard</a>
 as can be seen in publicly available <a href="link to blog post or whatever">benchmarks</a>.`
