### ISSUE TITLE
jekyll build failing since change from minima_social_icons.svg to minima_social_icons.html

### ISSUE THREAD

**Issue by faceyneck** [jekyll/minima#687]
If I comment out `social_links`, Jekyll will build properly.

Cloning the repository that I used for my GitHub Pages site, and running `jekyll build` will fail with error:

```
Invalid syntax for include tag. File contains invalid characters or sequences: (Argument Error)
social-icons/.svg
```

**Comment by 3dgiordano** [comment]
The same problem with GitHub Pages.

The following commit brake the backwards compatibility

https://github.com/jekyll/minima/pull/686#issuecomment-1311972381

**Comment by faceyneck** [comment]
After some messing around, I'm able to get Jekyll to build by changing the `social_links` to the key/value pairs, as described in the current README.md for minima.

However, they do not display.
![minima_problems](https://user-images.githubusercontent.com/20979112/201442263-3708ec42-6a70-42f9-bc5e-0c7455df55f6.png)

**Comment by 3dgiordano** [comment]
Thanks @faceyneck 

I did the same update in the social links declaration and it solved the problem.

A message in the build explaining how to migrate the format or check the format of social links could help users understand how to solve the problem.

**Comment by faceyneck** [comment]
> Thanks @faceyneck 
> 
> I did the same update in the social links declaration and it solved the problem.
> 
> A message in the build explaining how to migrate the format or check the format of social links could help users understand how to solve the problem.
> 
> 

Absolutely!

So, I've now got social links working, but the RSS icon is missing.

Can't find anything about this in the README.

**Comment by ashmaroli** [comment]
To all remote-theme users landing here to resolve failing builds, either follow the steps in above comments or please lock your builds to last known working commit on the master branch of this repository by following the associated instructions in the `jekyll-remote-theme` documentation.

There may be more of such breaking changes in the coming days / weeks.

Regarding the missing `rss` icon for users building with the latest commit on `master`, please add a similar declaration for the rss icon under the `minima.social_links` config key. I admit, it will not render in the previous location at the top of the footer. (I intend to remove the `"Subscribe.."` with a future pull request.)

**Comment by faceyneck** [comment]
Thanks @ashmaroli,
I appreciate you taking the time to comment and help us out.

**Comment by harisont** [comment]
> Regarding the missing `rss` icon for users building with the latest commit on `master`, please add a similar declaration for the rss icon under the `minima.social_links` config key. I admit, it will not render in the previous location at the top of the footer. (I intend to remove the `"Subscribe.."` with a future pull request.)

What do you mean exactly? Something like

```
    - { platform: rss, user_url: https://harisont.github.io/feed.xml}
```

under `  social_links:`?
Because that creates a working link but no icon is displayed (what's the "platform"?)

**Comment by ashmaroli** [comment]
@harisont Yes, that is exactly what I meant:
```yaml
minima:
  social_links:
    - { platform: rss, user_url: "https://mysite.com/feed.xml" }
```
will render the RSS icon.
`platform` for the RSS icon is `rss`.

**Comment by harisont** [comment]
Right! With some inexplicable delay, it worked.
Thank you!

**Comment by sayakpaul** [comment]
> After some messing around, I'm able to get Jekyll to build by changing the `social_links` to the key/value pairs, as described in the current README.md for minima.
> 
> However, they do not display. ![minima_problems](https://user-images.githubusercontent.com/20979112/201442458-9767e3f6-bb4d-47cb-aa8d-ef9445210ded.png)

This worked like a charm for me. Thank you!

**Comment by Hyrtsi** [comment]
I had the same issue. Updating my `social_links` to follow the [new format](https://github.com/jekyll/minima#social-networks) fixed it. I didn't have to do anything else.
