### ISSUE TITLE
Invalid syntax for include tag in minima-social-icons.html

### ISSUE THREAD

**Issue by ankschoubey** [jekyll/minima#688]
Hi, I recently started receiving this issue:

```
Liquid Exception: Invalid syntax for include tag. File contains invalid characters or sequences: social-icons/.svg Valid syntax: {% include file.ext param='value' param2='value' %} in assets/minima-social-icons.html
```
Source: https://github.com/ankschoubey/blog/actions/runs/3455529446/jobs/5767615577

It seems the file was updated 2 days ago. And GitHub Action cannot evaluate: `{% assign key = entry.platform -%}` properly. in the following file: https://github.com/jekyll/minima/blob/master/assets/minima-social-icons.html

**Comment by ashmaroli** [comment]
Yes @ankschoubey, there has been a syntax change. Please refer the documentation and current state of the `_config.yml` file in the `master` 
branch of this repository.

**Comment by MichaelGrafnetter** [comment]
Hi, having the same issue when using `jekyll/minima` as remote theme.
```
Generating...
Remote Theme: Using theme jekyll/minima
  Liquid Exception: Invalid syntax for include tag. File contains invalid characters or sequences: social-icons/.svg Valid syntax: {% include file.ext param='value' param2='value' %} in assets/minima-social-icons.html
jekyll 3.9.2 | Error:  Invalid syntax for include tag. File contains invalid characters or sequences:

  social-icons/.svg

Valid syntax:

  {% include file.ext param='value' param2='value' %}
...
```

**Comment by ankschoubey** [comment]
Thanks @ashmaroli  

It worked.

I replaced the old format with the new one: https://github.com/ankschoubey/blog/commit/08b25adc4f74e1d4d1f9b34a571fdb5be09b7a39
