### ISSUE TITLE
Configuring time format

### ISSUE THREAD

**Issue by ward** [jekyll/minima#69]
I notice that the time format in _layouts/home.html and _layouts/post.html is hardcoded. Is it possible/would it make sense to make this configurable in _config.yml?

Am I correct that right now my main option to change the format is to make a copy of those files and edit those copies?

**Comment by DirtyF** [comment]
@ward you're correct about the copy part. 

Are you interested in submitting a PR to handle date format in configuration file?

**Comment by ward** [comment]
Sure, I can take a look at it. I should have some time for it over the weekend.

**Comment by ward** [comment]
Well I looked at it on the tram home and it seemed simple enough. https://github.com/jekyll/minima/pull/70
