### ISSUE TITLE
RSS icon depends on "rss" social_link, but "Subscribe" link does not

### ISSUE THREAD

**Issue by troy** [jekyll/minima#692]
The [footer](https://github.com/jekyll/minima/blob/master/_includes/footer.html#L11) generates a "Subscribe" link and an RSS icon. That icon comes from a [dynamically generated](https://github.com/jekyll/minima/blob/master/assets/minima-social-icons.html) set with one icon symbol per `social_links` config entry. As far as I can tell, if `social_links` doesn't contain an `rss` entry, the RSS icon won't be included in the file.

If this explanation is accurate and there's no quick fix, perhaps add a comment/explanation in the default config file `social_links` section.

**Comment by ashmaroli** [comment]
I planned on removing the `Subscribe` link entirely in a subsequent pull request at the time, but now can't seem to convince myself to do it :sweat_smile:

**Comment by SNMetamorph** [comment]
Yes, I faced with this issue too
