### ISSUE TITLE
Jekyll SEO - Question

### ISSUE THREAD

**Issue by Ingolfurinn** [jekyll/minima#707]
Hello!

This is more of a question rather than an actual issue.

The README, says

> Minima comes with [jekyll-seo-tag](https://github.com/jekyll/jekyll-seo-tag) plugin preinstalled to make sure your website gets the most useful meta tags.

while the Jekyll documentation 

> [GitHub Pages](https://pages.github.com/) is powered by Jekyll. All GitHub Pages sites are generated using the  --safe option to disable plugins (with the exception of some [whitelisted plugins](https://pages.github.com/versions)) for security reasons. Unfortunately, this means your plugins won't work if you’re deploying via GitHub Pages.

Now, the [jekyll-seo-tag](https://github.com/jekyll/jekyll-seo-tag) plugin is on the whitelist. Does this mean that, even if I am deploying via GitHub Pages, it will still work?

Thank you for your time.

**Comment by ashmaroli** [comment]
Hello @Ingolfurinn
Yes, your observation is correct. `jekyll-seo-tag` will work with Minima and GitHub Pages out-of-the-box. You may even "try" unreleased changes to the theme by using the `jekyll-remote-theme` plugin.

However, the GitHub Pages native build using a very old version of Jekyll, has taken a back seat when they introduced the ability to set up GitHub Actions to handle build and deploy.

**Comment by Ingolfurinn** [comment]
Nice, thank you for your exhaustive and fast reply. 
I will close the issue now.
