### ISSUE TITLE
Remove `suscribe via RSS` from _layouts/home.html

### ISSUE THREAD

**Issue by denniscmartin** [jekyll/minima#747]
Hello.

I'm trying to remove the "suscribe via RSS" text below my blog posts. 

## What I've tried

Following instructions from other issues related to mine:
- I copied `_includes/footer.html` from the minima repository
- deleted `feed-subscribe` block, and place it in `_includes/footer.html` in my project. 
- deleted `gem "jekyll-feed", "~> 0.12"` from `Gemfile`
- deleted `jekyll-feed` from `plugins:` in `_config.yml`

However, the message is still apearing just below my posts. 
You can check it in the following image or just visiting my demo [website](https://denniscmartin.github.io/)

![Screenshot from 2023-08-01 18-00-56](https://github.com/jekyll/minima/assets/66180929/7dc412a5-8577-45b0-904b-5cb20cf46daf)

Inspecting the "suscribe via RSS" message in my [website](https://denniscmartin.github.io/) you can see this block:

```html
<p class="rss-subscribe">
subscribe <a href="[/feed.xml](view-source:https://denniscmartin.github.io/feed.xml)">via RSS</a>
</p>
```
Checking `_layouts/home.html` in the minima repository, I cannot see the `rss-suscribe` block. So, my questions are:

- How is it being rendered?
- How can I remove it?

Thank you.

**Comment by MarvinVoV** [comment]
I encountered the same problem.

**Comment by 4332weizi** [comment]
Hi, have you been able to find any solutions?
