### ISSUE TITLE
Sass files not available by default

### ISSUE THREAD

**Issue by DevOpsJeremy** [jekyll/minima#752]
The section [Customizing templates](https://github.com/jekyll/minima#customizing-templates) instructs to simply create an `assets/css/style.scss` file and, optionally, `_sass/minima/custom-styles.scss` & `custom-variables.scss`. However, the build fails without the remaining Sass files since they are referenced in `style.scss`.

### Example 1
After adding `assets/css/style.scss` and populating it with the following in accordance with [Customizing templates](https://github.com/jekyll/minima#customizing-templates):

```scss
---
---

@import
  "minima/skins/{{ site.minima.skin | default: 'classic' }}",
  "minima/initialize";
```
[The build](https://github.com/DevOpsJeremy/DevOpsJeremy.github.io/actions/runs/5946003242/job/16125927392) failed with the following error:
> Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/style.scss':
File to import not found or unreadable: minima/skins/classic. Load paths: /usr/local/bundle/gems/minima-2.5.1/_sass /usr/local/bundle/gems/minima-2.5.1/_sass on line 2

Log file: [Example 1.txt](https://github.com/jekyll/minima/files/12414430/Example.1.txt)
### Example 2
After adding the [skins](https://github.com/jekyll/minima/tree/master/_sass/minima/skins) to `_sass/minima/skins`, [the build](https://github.com/DevOpsJeremy/DevOpsJeremy.github.io/actions/runs/5946049470/job/16126033188) still failed with the following error:
> Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/style.scss':
File to import not found or unreadable: minima/initialize. Load paths: /github/workspace/_sass /usr/local/bundle/gems/minima-2.5.1/_sass /usr/local/bundle/gems/minima-2.5.1/_sass on line 3

Log file: [Example 2.txt](https://github.com/jekyll/minima/files/12414429/Example.2.txt)

---
Of course, manually adding the Sass source files resolves this issue, but this overrides the "defaults" and the files should be available without having to manually include them, so that the site stays "[in sync with upstream changes released in future versions](https://github.com/jekyll/minima#customizing-templates:~:text=in%20sync%20with%20upstream%20changes%20released%20in%20future%20versions)".

**Comment by mvallebr** [comment]
I am new to minima and I am having this problem as well - any short term workaround?

**Comment by ashmaroli** [comment]
The README instructions you're referring to is for the unreleased Minima 3.0. To view instructions for v2.5.x, change the repository branch / tree accordingly.
