### ISSUE TITLE
Skins don't persist when switching subpage

### ISSUE THREAD

**Issue by patrykpalej** [jekyll/minima#763]
**The problem:**
I enter the [minima demo site](https://jekyll.github.io/minima/) and switch skin to another one. Then I change a subpage, e.g. opening a blogpost and the skin is not persisted.

Is it a bug or a feature? How can it be fixed?

---

Btw. on the main branch switching skins in not implemented. It's done on demo-site branch, however its structure is different. Which of these branches should be used as a starter?

**Comment by MarcoJanse** [comment]
I noticed the same on the demo site, and I am struggling with getting these skins active on my own site. According to the README, skins is a feature in minima 3.0, and the latest release is 2.5.1, so I assume this is not released yet?

**Comment by ashmaroli** [comment]
Hello,
The demo-site is just a pointer to showcase the available skins in this theme. It is not meant to be a starter.

Use the `master` branch as the starter to Minima v3 (still unreleased and unstable) or run `jekyll new <path>` locally to create a scaffolding with Minima 2.5
