### ISSUE TITLE
Use different syntax highlighting style

### ISSUE THREAD

**Issue by lunaryorn** [jekyll/minima#77]
How do I change the syntax highlighting style when using minima as a theme gem?

I tried to define my own `_sass/minima/syntax-highlighting.scss` but it doesn't seem to get picked up by Jekyll.  I could define my own stylesheet to `@import` in `assets/main.scss` but then I'd have to undo all of minima's syntax highlighting theme, which quickly gets tedious.

What's the recommended way here?

**Comment by ashmaroli** [comment]
Rather very simple actually:
  - **copy** `<minima>/_sass/minima/_syntax-highlighting.scss` to your **source.root**
  - **edit** `<source>/_sass/minima/_syntax-highlighting.scss` and save.
  - `bundle exec jekyll serve`

**Comment by lunaryorn** [comment]
@ashmaroli I'm sorry but as I said that did not work for me.  I have `_sass/minima/_syntax-highlighting.scss` with the following contents (just to make sure it works) but it's not picked up:

```
body {
  color: red;
}
```

I don't even get a syntax error if I put invalid SCSS into that file—Jekyll seems to entirely ignore the file.

**Comment by ashmaroli** [comment]
do you have the source code online?

**Comment by lunaryorn** [comment]
Forgot to say, that other partials from `_sass` are picked up just fine.  For instance, I've got `_sass/solarized/_palette.scss` with solarized color definitions, and I can perfectly import and use it via `@import "solarized/palette.scss"` from `assets/main.scss`.

**Comment by lunaryorn** [comment]
@ashmaroli I just pushed my attempt to https://github.com/lunaryorn/lunaryorn.github.io/tree/try-override-minima-syntax-highlighting

**Comment by lunaryorn** [comment]
@ashmaroli See https://github.com/lunaryorn/lunaryorn.github.io/commit/e8fe2aafcbdd0248a8d6967035eb7713fede3cf9.

The site has no special deps, just standard github pages.  You can build it with:

```
$ bundle install
$ bundle exec jekyll serve
```

**Comment by ashmaroli** [comment]
okay.. it seems like the bug is actually in our documentation.. 
since our `main.scss` actually `@imports "minima";` which is within the theme-gem, our overrides are not being detected.. unless our `_sass` dir **at source** also has a `minima.scss`

**Comment by ashmaroli** [comment]
## workaround
When attempting to override minima's partials, include a **`minima.scss`** inside the **`_sass` dir at source** as well.

**Comment by lunaryorn** [comment]
@ashmaroli So, I'd have to copy the entire `minima.scss` over to `_sass`?

**Comment by ashmaroli** [comment]
its just one more file IMO.. or set an `@import "minima/syntax-highlighting";` directive after 
`@import "minima";`

**Comment by lunaryorn** [comment]
If I import the partial explicitly I'd still have to undo all of minima's syntax highlighting, wouldn't I?  The original syntax highlighting would still be in effect wouldn't it?

I'm not happy with copying so many files:  The more I copy the less I'm actually using the theme and the harder it becomes to follow upstream changes.  If I copy the CSS I could as well just do my own design.

**Comment by ashmaroli** [comment]
copying the sass file over is to have the pre-defined classes and ids available to be easily altered. If you only want to override *some* of the pre-defined styles, then the best solution is to have all overrides defined in one stylesheet and then import that in your `main.scss` **after** the required imports:
```sass
@import
  "minima",
  "solarized/syntax"
  "style_overrides"
;
```

**Comment by lunaryorn** [comment]
@ashmaroli Yes, but if I do that I need to reset every styling from `minima/syntax-highlighting` *explicitly*, i.e. redefine `color` and `font-style`, etc. for every single element, don't I?  IOW I'm not starting from the predictable default styling, but from some arbitrary predefined styling, right?

**Comment by lunaryorn** [comment]
Maybe the better way to phrase my intent is: How can I completely disable Minima's syntax highlighting scheme, and have no syntax highlighting, without having to explicitly override every single style?

**Comment by ashmaroli** [comment]
your `main.scss` determines styles. Copy `main.scss` from the gem and replace the `@import` directive with the following:
```sass
/* <source>/assets/main.scss */
@import
  "minima/base",
  "minima/layout"
;
```
Dont import the entire `minima.scss'

**Comment by lunaryorn** [comment]
@ashmaroli But what about the `media-query` mixin?  It's defined in `minima.scss`…  wouldn't I need to copy it?  Or any mixin that get's define there in future releases of this theme?

**Comment by ashmaroli** [comment]
yes you'll need to copy over the minima-specific media-queries to your `main.scss`.
and yes, you wont have access to further upstream updates to `minima.scss`

**Comment by lunaryorn** [comment]
@ashmaroli I must admit that's not the solution I hoped for.  Is there a way that the theme could be changed to allow changes to the syntax highlighting without having to copy the main style file?

**Comment by ashmaroli** [comment]
changes to the syntax highlighting is still possible like I suggested earlier. But if you want to disable the entire partial and have your theme in sync with future updates is not possible.
The only way out is to import a partial that overrides each and every syntax-highlight definition to your liking..

**Comment by lunaryorn** [comment]
I understand.  I guess then minima is not for me. ☺️  Thank you for your patience.
