### ISSUE TITLE
Changing the default layout from `default` to `base` was a questionable idea

### ISSUE THREAD

**Issue by michaelnordmeyer** [jekyll/minima#771]
In https://github.com/jekyll/minima/pull/690 the default layout was renamed from `default.html` to `base.html`.

While the given rationale is not wrong, it ignores the [Jekyll documentation regarding layouts](https://jekyllrb.com/docs/layouts/):

> The convention is to have a base template called default.html and have other layouts [inherit](https://jekyllrb.com/docs/layouts/#inheritance) from this as needed.

There is a plugin called [jekyll-default-layout](https://github.com/benbalter/jekyll-default-layout), which is installed through the GitHub Pages gem [by default](https://pages.github.com/versions/).

A solution for having both was mentioned in https://github.com/jekyll/minima/pull/690#issuecomment-1435078904, but I don't think there's much to gain by having a layout called base instead of default. It most likely leads to more confusion.

I for one consider the default naming scheme to be more helpful, because it conveys the notion that this is the default layout, which will be used as default if nothing is declared, and is not extended with any particular functionality, which might only apply to a subset of pages.

What do you think?

**Comment by ashmaroli** [comment]
> because it conveys the notion that this is the default layout, which will be used as default if nothing is declared

This is the exact reason why I chose to rename `default.html` to `base.html`. The `jekyll-default-layout` is a GitHub Pages-specific extension and not a core Jekyll feature or functionality.
