### ISSUE TITLE
Underline and Number headings

### ISSUE THREAD

**Issue by gyanantaran** [jekyll/minima#778]
Hi, I have been trying to get something like this to work:

<img width="851" alt="Screenshot 2024-02-16 at 1 13 58 AM" src="https://github.com/jekyll/minima/assets/95016059/5894cb7b-27a2-4c40-85da-8ba2e139fd8d">

source: https://sohl-dickstein.github.io/2024/02/12/fractal.html

I am almost sure it is Minima. Please help me in getting this underline and number heading. Also note the footer. Is there any easy option for these academic-like blog writings?

Currently I have this:

<img width="916" alt="Screenshot 2024-02-16 at 1 16 54 AM" src="https://github.com/jekyll/minima/assets/95016059/af2e5597-2d8d-4fd1-a2f2-7b004821b003">

Please help.

**Comment by mattr-** [comment]
GitHub Issues are not the correct forum to ask for help. Please use https://talk.jekyllrb.com instead. Thanks!

**Comment by gyanantaran** [comment]
Sorry, solved it though.
