### ISSUE TITLE
Add icon for Codeberg social link

### ISSUE THREAD

**Issue by andrefelipeos** [jekyll/minima#787]
Currently, Minima does not support adding a Codeberg icon/social link.  

[Codeberg](https://codeberg.org/) is "a collaboration platform providing Git hosting and services for free and open source software, content and projects". They provide a logo-kit [here](https://codeberg.org/Codeberg/Design), under the Creative Commons CC0 license.

**Comment by mattr-** [comment]
Jekyll's maintainers aren't likely to add more icons/social links on their own, since we don't use 90% of them. If you want a social link for Codeberg, the most effective way is to open a pull request to add one so that we can review and merge it. Thanks!

**Comment by antoineco** [comment]
This was addressed in #788
