### ISSUE TITLE
header_pages doesnt work

### ISSUE THREAD

**Issue by FireRedDev** [jekyll/minima#798]
Hey! My header items dont show up when using layout home - not if i just use blog.md without the html document either (check it at christophergusenbauer.at/blog)
![image](https://github.com/user-attachments/assets/9eeef877-3e1e-4fa8-8469-5e3d03220a7e)
```
title: Christopher Gusenbauers Website
description: >- # this means to ignore newlines until "baseurl:"
  Christopher Gusenbauer ist ein oberösterreichischer Unternehmer, Entwickler und Content Creator
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://christophergusenbauer.at" # the base hostname & protocol for your site, e.g. http://example.com
header_pages:
  - index.html
  - blog.md

# Build settings
theme: minima
plugins:
  - jekyll-feed
```

**Comment by ashmaroli** [comment]
Hello @FireRedDev
Your repository contains `_includes/header.html` which overrode `<minima>/_includes/header.html` that contains the markup and logic for rendering the _header_pages_ feature.

You may rename your header include file to some other name to resolve this issue.
