### ISSUE TITLE
Social icon SoundCloud

### ISSUE THREAD

**Issue by PanderMusubi** [jekyll/minima#820]
Please support the [SoundCloud](https://www.svgrepo.com/svg/21451/soundcloud) social icon. The SVG is found at https://www.svgrepo.com/svg/21451/soundcloud

The username should be used as `https://soundcloud.com/USERNAME` (without `www.` and without trailing slash `/`)

**Comment by ashmaroli** [comment]
Sorry, Minima won't be supporting additional social platform icons.

**Comment by PanderMusubi** [comment]
Would a PR be welcomed?
