### ISSUE TITLE
Social icon Mixcloud

### ISSUE THREAD

**Issue by PanderMusubi** [jekyll/minima#821]
Please support the [Mixcloud](https://en.wikipedia.org/wiki/Mixcloud) social icon. The SVG is found at https://www.svgrepo.com/svg/306432/mixcloud

The username should be used as `https://www.mixcloud.com/USERNAME/` (with `www.` and with trailing slash `/`)

**Comment by ashmaroli** [comment]
Sorry, Minima won't be supporting additional social platform icons.
