### ISSUE TITLE
Social icon Odysee

### ISSUE THREAD

**Issue by PanderMusubi** [jekyll/minima#822]
Please support the [Odysee](https://en.wikipedia.org/wiki/Odysee) social icon. The SVG is found at https://www.svgrepo.com/svg/504680/odysee

The username should be used as https://odysee.com/@USERNAME (without `www.` and with `:` + decimal at the end of the username and without trailing slash `/`)

An example is https://odysee.com/@jekyll:2 where USERNAME is `jekyll:2`

**Comment by ashmaroli** [comment]
Sorry, Minima won't be supporting additional social platform icons.
