### ISSUE TITLE
why custom-head.html doesn't work

### ISSUE THREAD

**Issue by xiaoyuzhzh** [jekyll/minima#823]
I created a custom-head.html file myself, but the Link tags inside it are not being included in the head of each page.
Here's my repository https://github.com/xiaoyuzhzh/xiaoyuzhzh.github.io

**Comment by xiaoyuzhzh** [comment]
Am I create wrong folder？I do have it，I left my repository。

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by xiaoyuzhzh** [comment]
sorry ，I missed the name. so I need to create a  empty _layout folder, right?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by xiaoyuzhzh** [comment]
I checked my project, and indeed there is an empty _layouts folder in my local branch, but it still hasn’t taken effect. Can you tell me the specific reason why?
![image](https://github.com/user-attachments/assets/0139e0e2-1d4d-4a31-b032-465a4e937f6c)

**Comment by SwitWu** [comment]
Create `default.html` in `_layouts` and write like:

```html
<!DOCTYPE html>
<html lang="{{ page.lang | default: site.lang | default: "en" }}">

  {%- include custom-head.html -%}

  <body>

    {%- include header.html -%}

    <main class="page-content" aria-label="Content">
      <div class="wrapper">
        {{ content }}
      </div>
    </main>

    {%- include footer.html -%}

  </body>

</html>
```

**Comment by xiaoyuzhzh** [comment]
I tried creating this file, and it indeed allows me to include my custom header, but then the original CSS files are not being included anymore.
![image](https://github.com/user-attachments/assets/bfe8ee56-0daf-4759-8d26-477109c96a1b)

**Comment by SwitWu** [comment]
1. Copy the `\_sass` folder from the official repo into your root directory.
2. Add `<link rel="stylesheet" href="{{ '/assets/main.css' | relative_url }}">` to the `custom-head.html`
3. `jekyll serve` again

**Comment by xiaoyuzhzh** [comment]
It works, thank you!!!
