### ISSUE TITLE
Latex integration with custom-head.html

### ISSUE THREAD

**Issue by rcortes100** [jekyll/minima#828]
Hi!
I would love to use this template with LaTeX integration. I found that the way to do it was to add the following lines:

```   <!-- MathJax -->
    <script type="text/javascript"
      src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.3/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
    </script>
```
into the header of the base.html file.

In the README it is stated that such customizations can be done by editing the _includes/custom-head.html file, so I added it to my page. However, it is not working.

I didn't clone the whole theme, I just included the minima gem in the Gemfile, and everyting works ok, but I just want to have the LaTeX integration.

I fear that the only way to do it is then to clone the whole repository, but I would rather not because I wouldn't like to have to copy everything each time a new release is done.

Is there a way to make this work without having to copy the whole Minima repository?

This is the page I am working on: [https://github.com/rcortes100/pagina_latex](https://github.com/rcortes100/pagina_latex)

Thanks for your attention!

**Comment by ashmaroli** [comment]
Ideally Jekyll should load `<your-source-dir>_includes/custom-head.html` and ignore the namesake in theme-gem or remote-theme location.

However, the `custom-head.html` include-file is part of unreleased changes. Therefore, a simple `gem "minima"` would not contain the necessary directive to load the include-file.

The solution is to **either**:
- point gem directive to this repository:
   ```diff
   - gem "minima"
   + gem "minima", github: "jekyll/minima"
   ```
- (or) consume the theme via the `jekyll-remote-theme` plugin. (Refer plugin docs for instructions.)

**Comment by rcortes100** [comment]
Thanks you so much, I followed your instructions, and I was able to do so. I had to add the gem directive to the Gemfile, and then setup Github Actions as indicated here:
[https://jekyllrb.com/docs/continuous-integration/github-actions/](https://jekyllrb.com/docs/continuous-integration/github-actions/)
