### ISSUE TITLE
explain layout usage

### ISSUE THREAD

**Issue by dret** [jekyll/minima#87]
it would be helpful to explain which layout to use for what kind of content/page in the README document. it is not quite clear what the four defined layouts are supposed to be used for, and if/how they relate.

**Comment by ashmaroli** [comment]
@dret Hi, I've opened a pull to update our documentation.. Do refer the changed file and provide feedback if something's not still clear.. Thanks :smiley:

**Comment by ashmaroli** [comment]
This has been resolved. Is it not?

**Comment by dret** [comment]
i think so. thanks a lot, @ashmaroli!
