### ISSUE TITLE
feed is broken

### ISSUE THREAD

**Issue by dret** [jekyll/minima#89]
out of the box it seems that the feed is broken. https://validator.w3.org/feed reports a missing author element.

**Comment by dret** [comment]
also, it seems that feed.xml gets served as `application/xhtml+xml` but it should be `application/atom+xml`.

**Comment by pathawks** [comment]
Minima is now using the **jekyll-feed** plugin :+1:

**Comment by dret** [comment]
On 2016-11-29 14:14, Pat Hawks wrote:
> Minima is now using the *jekyll-feed* plugin 👍

that's kind of funny. i remember testing this a little while ago and 
then ditching it because the feeds they generated were broken. well, it 
seems they still are...

**Comment by dret** [comment]
closing as the right place to submit this is jekyll-feed: https://github.com/jekyll/jekyll-feed/issues/146
