### ISSUE TITLE
Broken link to /feed.xml out-of-the-box.

### ISSUE THREAD

**Issue by gsnedders** [jekyll/minima#98]
Out of the box, minima produces a broken link to `/feed.xml`, because it requires jekyll-feed. Minima should either depend on jekyll-feed or not output the link to the feed.

**Comment by pathawks** [comment]
For reference, [here is the offending line](https://github.com/jekyll/minima/blob/v2.1.0/_includes/head.html#L11)

**Comment by DirtyF** [comment]
@pathawks I was thinking of adding jekyll-feed as a runtime dependency in the gemspec, modify example Gemfile and _config.yml and use feed meta instead in the include, do this seem OK to you?

On a side note, an `html-proofer` test of the output wouldn't hurt to avoid this.

**Comment by pathawks** [comment]
I seem to remember their being an intentional decision _not_ to tie **minima** to **jekyll-feed**, as **minima** is supposed to be a minimal.

Can't find that thread now.

**Comment by gsnedders** [comment]
I for one would rather it not be a dependency, FWIW, especially for sites which don't have any posts (i.e., consist merely of pages and collections).

**Comment by alzeih** [comment]
As a workaround, I used this in `_layouts/home.html`:

```
  {% if site.gems contains "jekyll-feed" %}
    <p class="rss-subscribe">subscribe <a href="{{ "/feed.xml" | relative_url }}">via RSS</a></p>
  {% endif %}
```

**Comment by alzeih** [comment]
There's (only) one more place that references feed.xml:

`_includes/head.html`contains

```  <link rel="alternate" type="application/rss+xml" title="{{ site.title | escape }}" href="{{ "/feed.xml" | relative_url }}">```

So perhaps this should be guarded with a check also?

**Comment by ashawley** [comment]
If you use `jekyll new`, then you get the dependency for `jekyll-feed`:

See https://github.com/jekyll/jekyll/blob/af5d096/lib/site_template/_config.yml#L31

So someone just forgot to add that dependency when the theme was forked to this repo last year?

**Comment by ashmaroli** [comment]
> @DirtyF: I was thinking of adding jekyll-feed as a runtime dependency
> @pathawks: ..an intentional decision not to tie **minima** to **jekyll-feed** as **minima** is supposed to be a minimal.

Is the above still valid, esp. since Minima will now come with `jekyll-seo-tag` included?

**Comment by alzeih** [comment]
I think minima should really be minimal, and not require jekyll-feed or jekyll-seo-tag (or any other jekyll plugins).

If that's not possible, I think it should at least degrade gracefully. 

Maybe the default jekyll post could contain instructions (or a link to docs) for finding and installing plugins?
https://github.com/jekyll/jekyll/blob/master/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb

**Comment by ashawley** [comment]
Yeah, hopefully the "degrade gracefully" fix in #129 gets merged since `jekyll new` currently sets the theme to `minima` and adds `jekyll-feed`.

**Comment by alzeih** [comment]
@ashawley: I've asked for the remove option in #182, for the reasons I've outlined there. 

If this patch gets accepted, and the `minima` gem is released with this patch, then the Jekyll `site_template/_config.yml` should probably drop `jekyll-feed` too. However the extra plugin probably won't break anything, so if this takes a while to be removed from the `_config.yml` it shouldn't be a problem. (or left there as an example of how to use plugins).

`jekyll-feed`'s documentation is fairly good, as is Jekyll's on plugins. I think the effort in adding a plugin and configuring it is less effort than obtaining, modifying and maintaining two `minima` template files in every jekyll app that uses `minima` for OOTB to not 404. That does depend on whether most users use RSS or not though.

Graceful degradation is limited by some technical reasons of Jekyll. The one's I can think of off hand are the multiple places plugins are enabled (`site.gems`, `site.plugins`, `Gemfile`, `_plugins`), and something to do with how liquid handles missing tags guarded by if checks still crashes. These seem like issues that are much harder to solve right now, but if these are fixed then I'd be absolutely for graceful degradation.

**Comment by ashawley** [comment]
Last I checked, `site.gems` will work with `Gemfile` and is forwards compatible with the new `site.plugins`.  But this should be taken up at #129 and discussed there.  There's no disputing that minima is broken out of the box as this issue documents.

**Comment by alzeih** [comment]
Yep, you're right about `site.gems` and `site.plugins`. I've no idea how to query for plugins enabled in a `Gemfile` with the `:jekyll-plugins` group though.

**Comment by ashmaroli** [comment]
> I've no idea how to query for plugins enabled in a `Gemfile` with the `:jekyll-plugins` group though.

The fact is that you **cannot** query for plugins activated via `:jekyll_plugins` group..
Its a convenience block.. same as how Jekyll 3.5 onwards will automatically activate a theme's whitelisted `runtime_dependencies`
